### ISSUE TITLE
Stremio 4.4.25-1 not working on Ubuntu 18.04

### ISSUE THREAD

**Issue by mikibakaiki** [Stremio/stremio-bugs#177]
I've got it running on an ubuntu machine, same software and version, but now i cant make it run on another machine! I downloaded the new .deb, i tried already copying the .deb i used in the machine that it's working, i tried to create the folder `~/.stremio-server` cause it was missing, and it kinda started, asked for login, but got stuck there.

Some of the errors that i run into:

```
hls executables located ->  { ffmpeg: '/usr/bin/ffmpeg', ffsplit: null }
Using app path -> /home/mikibakaiki/.stremio-server
Enabling casting...
Discovery of new external device "mpv" - MPV
{ Error: listen EADDRINUSE :::11470
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Object.require.660../cache (/opt/stremio/server.js:119148:8)
    at s (/opt/stremio/server.js:1:400)
    at e (/opt/stremio/server.js:1:571)
    at Object.<anonymous> (/opt/stremio/server.js:1:589)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 11470 }
{ Error: listen EADDRINUSE :::12470
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Object.require.660../cache (/opt/stremio/server.js:119168:9)
    at s (/opt/stremio/server.js:1:400)
    at e (/opt/stremio/server.js:1:571)
    at Object.<anonymous> (/opt/stremio/server.js:1:589)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 12470 }
{ Error: listen EADDRINUSE :::11471
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Server.<anonymous> (/opt/stremio/server.js:119151:53)
    at emitOne (events.js:116:13)
    at Server.emit (events.js:211:7)
    at emitErrorNT (net.js:1387:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 11471 }
{ Error: listen EADDRINUSE :::11472
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Server.<anonymous> (/opt/stremio/server.js:119151:53)
    at emitOne (events.js:116:13)
    at Server.emit (events.js:211:7)
    at emitErrorNT (net.js:1387:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 11472 }
EngineFS server started at http://127.0.0.1:11473
-> /home/mikibakaiki/Downloads/kali-linux-2018.3a-amd64.iso.torrent: discovered
-> /home/mikibakaiki/Downloads/kali-linux-2018.3a-amd64.iso.torrent: already indexed
stremio: ../nouveau/pushbuf.c:723: nouveau_pushbuf_data: Assertion `kref' failed.
```

```
nouveau: kernel rejected pushbuf: Invalid argument
nouveau: ch19: krec 0 pushes 1 bufs 8 relocs 0
nouveau: ch19: buf 00000000 0000003a 00000002 00000002 00000000
nouveau: ch19: buf 00000001 0000005a 00000002 00000002 00000000
nouveau: ch19: buf 00000002 00000008 00000002 00000000 00000002
nouveau: ch19: buf 00000003 000000b3 00000002 00000002 00000000
nouveau: ch19: buf 00000004 00000058 00000002 00000002 00000000
nouveau: ch19: buf 00000005 000000b2 00000002 00000002 00000000
nouveau: ch19: buf 00000006 000000b4 00000002 00000002 00000000
nouveau: ch19: buf 00000007 00000025 00000002 00000002 00000000
nouveau: ch19: psh 00000009 000007602c 0000076464
nouveau: 	0x200308e0
nouveau: 	0x00010000
nouveau: 	0x00000000
nouveau: 	0x005a0000
nouveau: 	0xa01508e3
nouveau: 	0x00000000
nouveau: 	0x3aaaaaab
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0xbb1baadf
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0xbf800000
nouveau: 	0x3f800000
nouveau: 	0x00000000
nouveau: 	0x3f800000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x20024062
nouveau: 	0x00000000
nouveau: 	0x00672020
nouveau: 	0x20024060
nouveau: 	0x00000020
nouveau: 	0x00000001
nouveau: 	0xa009406c
nouveau: 	0x00001001
nouveau: 	0x58d24908
nouveau: 	0x06600000
nouveau: 	0x00600000
nouveau: 	0x00070020
nouveau: 	0xe880003f
nouveau: 	0x8000017f
nouveau: 	0x03000000
nouveau: 	0x00000000
nouveau: 	0x200104cd
nouveau: 	0x00000000
nouveau: 	0x200308e0
nouveau: 	0x00010000
nouveau: 	0x00000000
nouveau: 	0x00640000
nouveau: 	0x200208e3
nouveau: 	0x00000020
nouveau: 	0x00000101
nouveau: 	0x20030700
nouveau: 	0x00001010
nouveau: 	0x00000000
nouveau: 	0x00728600
nouveau: 	0x200207c0
nouveau: 	0x00000000
nouveau: 	0x0072865b
nouveau: 	0x20030704
nouveau: 	0x00001004
nouveau: 	0x00000000
nouveau: 	0x00728640
nouveau: 	0x200207c2
nouveau: 	0x00000000
nouveau: 	0x0072865b
nouveau: 	0x80000708
nouveau: 	0x20010586
nouveau: 	0x00000005
nouveau: 	0x6002057c
nouveau: 	0x00010000
nouveau: 	0x00030002
nouveau: 	0x80000585
nouveau: 	0x20020381
nouveau: 	0x06000000
nouveau: 	0x034a0000
nouveau: 	0x200308e0
nouveau: 	0x00010000
nouveau: 	0x00000000
nouveau: 	0x005a0000
nouveau: 	0xa01508e3
nouveau: 	0x00000000
nouveau: 	0x3aaaaaab
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0xbb1baadf
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0xbf800000
nouveau: 	0x3f800000
nouveau: 	0x00000000
nouveau: 	0x3f800000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x200308e0
nouveau: 	0x00010000
nouveau: 	0x00000000
nouveau: 	0x00640000
nouveau: 	0x200208e3
nouveau: 	0x00000020
nouveau: 	0x000000f5
nouveau: 	0x20030700
nouveau: 	0x00001010
nouveau: 	0x00000000
nouveau: 	0x0001e600
nouveau: 	0x200207c0
nouveau: 	0x00000000
nouveau: 	0x0001e65b
nouveau: 	0x20030704
nouveau: 	0x00001004
nouveau: 	0x00000000
nouveau: 	0x0001e640
nouveau: 	0x200207c2
nouveau: 	0x00000000
nouveau: 	0x0001e65b
nouveau: 	0x80000708
nouveau: 	0x20010586
nouveau: 	0x00000005
nouveau: 	0x6002057c
nouveau: 	0x00010000
nouveau: 	0x00030002
nouveau: 	0x80000585
nouveau: 	0x20020810
nouveau: 	0x00000011
nouveau: 	0x0007f3b0
nouveau: 	0x20010813
nouveau: 	0x00000007
nouveau: 	0x800101d5
nouveau: 	0x20020850
nouveau: 	0x00000051
nouveau: 	0x0007f230
nouveau: 	0x20010853
nouveau: 	0x00000004
nouveau: 	0x200200d8
nouveau: 	0x20164010
nouveau: 	0x00000020
nouveau: 	0x2001065b
nouveau: 	0x00000000
nouveau: 	0x200308e0
nouveau: 	0x00010000
nouveau: 	0x00000000
nouveau: 	0x005a0000
nouveau: 	0xa01508e3
nouveau: 	0x00000000
nouveau: 	0x3aaaaaab
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0xbb1baadf
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0xbf800000
nouveau: 	0x3f800000
nouveau: 	0x00000000
nouveau: 	0x3f800000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x200308e0
nouveau: 	0x00010000
nouveau: 	0x00000000
nouveau: 	0x005e0000
nouveau: 	0xa00508e3
nouveau: 	0x00000000
nouveau: 	0x3ee66666
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x200308e0
nouveau: 	0x00010000
nouveau: 	0x00000000
nouveau: 	0x00640000
nouveau: 	0x200208e3
nouveau: 	0x00000020
nouveau: 	0x000000f6
nouveau: 	0x20030700
nouveau: 	0x00001010
nouveau: 	0x00000000
nouveau: 	0x0001e500
nouveau: 	0x200207c0
nouveau: 	0x00000000
nouveau: 	0x0001e55b
nouveau: 	0x20030704
nouveau: 	0x00001004
nouveau: 	0x00000000
nouveau: 	0x0001e540
nouveau: 	0x200207c2
nouveau: 	0x00000000
nouveau: 	0x0001e55b
nouveau: 	0x80000708
nouveau: 	0x20010573
nouveau: 	0x00000000
nouveau: 	0x20010586
nouveau: 	0x00000005
nouveau: 	0x6002057c
nouveau: 	0x00010000
nouveau: 	0x00030002
nouveau: 	0x80000585
nouveau: 	0x200308e0
nouveau: 	0x00010000
nouveau: 	0x00000000
nouveau: 	0x005a0000
nouveau: 	0xa01508e3
nouveau: 	0x00000000
nouveau: 	0x3aaaaaab
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0xbb1baadf
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0xbf800000
nouveau: 	0x3f800000
nouveau: 	0x00000000
nouveau: 	0x3f800000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x200308e0
nouveau: 	0x00010000
nouveau: 	0x00000000
nouveau: 	0x00640000
nouveau: 	0x200208e3
nouveau: 	0x00000020
nouveau: 	0x000000f7
nouveau: 	0x20030700
nouveau: 	0x00001010
nouveau: 	0x00000000
nouveau: 	0x0072d600
nouveau: 	0x200207c0
nouveau: 	0x00000000
nouveau: 	0x0072d65b
nouveau: 	0x20030704
nouveau: 	0x00001004
nouveau: 	0x00000000
nouveau: 	0x0072d640
nouveau: 	0x200207c2
nouveau: 	0x00000000
nouveau: 	0x0072d65b
nouveau: 	0x80000708
nouveau: 	0x20010586
nouveau: 	0x00000005
nouveau: 	0x6002057c
nouveau: 	0x00010000
nouveau: 	0x00030002
nouveau: 	0x80000585
nouveau: 	0x200406c0
nouveau: 	0x00000000
nouveau: 	0x00014000
nouveau: 	0x00000454
nouveau: 	0x1000f010
```

I actually managed to do the login, but immediatly crashed...

Tell me if i can help with more errors or something :)

**Comment by Ivshti** [comment]
Sounds like a GPU driver issue

you're running nouveau - we've seen this before; switching to the native NVIDIA driver should solve it
