### ISSUE TITLE
Stremio 4.4.106-1 do not load. Stuck on loading screen

### ISSUE THREAD

**Issue by vejeta** [Stremio/stremio-bugs#225]
The system: Debian Buster(Testing) with kernel 5.6.11 x86_64 GNU/Linux

The logs show
```
[96066:96094:0509/232456.836863:ERROR:nss_util.cc(748)] After loading Root Certs, loaded==false: NSS error code: -8018
hls executables located ->  { ffmpeg: '/usr/bin/ffmpeg', ffsplit: null }
Using app path -> /home/user/.stremio-server
Enabling casting...
Discovery of new external device "vlc" - VLC
Discovery of new external device "mpv" - MPV
EngineFS server started at http://127.0.0.1:11470
EngineFS HTTPS endpoint at https://local.strem.io:12470
SSDP error: { type: 'ssdp',
  error:
   { type: 'send',
     error:
      { Error: send EPERM 239.255.255.250:1900
          at SendWrap.afterSend [as oncomplete] (dgram.js:467:11)
        errno: 'EPERM',
        code: 'EPERM',
        syscall: 'send',
        address: '239.255.255.250',
        port: 1900 } } }
SSDP error: { type: 'ssdp',
  error:
   { type: 'send',
     error:
      { Error: send EPERM 239.255.255.250:1900
          at SendWrap.afterSend [as oncomplete] (dgram.js:467:11)
        errno: 'EPERM',
        code: 'EPERM',
        syscall: 'send',
        address: '239.255.255.250',
        port: 1900 } } }
-> GET /settings 
-> GET /local-addon/catalog/other/local.json 
js: Failed to load https://stremio-porn.now.sh/stremioget/stremio/v1/q.json?b=eyJwYXJhbXMiOltudWxsLHsicXVlcnkiOnsidHlwZSI6Im1vdmllIn0sImxpbWl0IjoxMDAsInNvcnQiOnsicG9wdWxhcml0aWVzLnBvcm4uUG9ybkh1YiI6LTEsInBvcHVsYXJpdHkiOi0xfX1dLCJtZXRob2QiOiJtZXRhLmZpbmQiLCJpZCI6MSwianNvbnJwYyI6IjIuMCJ9: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://app.strem.io' is therefore not allowed access. The response had HTTP status code 451. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
js: Failed to load https://stremio-porn.now.sh/stremioget/stremio/v1/q.json?b=eyJwYXJhbXMiOltudWxsLHsicXVlcnkiOnsidHlwZSI6Im1vdmllIn0sImxpbWl0IjoxMDAsInNvcnQiOnsicG9wdWxhcml0aWVzLnBvcm4uWW91UG9ybiI6LTEsInBvcHVsYXJpdHkiOi0xfX1dLCJtZXRob2QiOiJtZXRhLmZpbmQiLCJpZCI6MSwianNvbnJwYyI6IjIuMCJ9: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://app.strem.io' is therefore not allowed access. The response had HTTP status code 451. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
js: Failed to load https://stremio-porn.now.sh/stremioget/stremio/v1/q.json?b=eyJwYXJhbXMiOltudWxsLHsicXVlcnkiOnsidHlwZSI6Im1vdmllIn0sImxpbWl0IjoxMDAsInNvcnQiOnsicG9wdWxhcml0aWVzLnBvcm4uUmVkVHViZSI6LTEsInBvcHVsYXJpdHkiOi0xfX1dLCJtZXRob2QiOiJtZXRhLmZpbmQiLCJpZCI6MSwianNvbnJwYyI6IjIuMCJ9: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://app.strem.io' is therefore not allowed access. The response had HTTP status code 451. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
js: Failed to load https://stremio-porn.now.sh/stremioget/stremio/v1/q.json?b=eyJwYXJhbXMiOltudWxsLHsicXVlcnkiOnsidHlwZSI6Im1vdmllIn0sImxpbWl0IjoxMDAsInNvcnQiOnsicG9wdWxhcml0aWVzLnBvcm4uU3BhbmtXaXJlIjotMSwicG9wdWxhcml0eSI6LTF9fV0sIm1ldGhvZCI6Im1ldGEuZmluZCIsImlkIjoxLCJqc29ucnBjIjoiMi4wIn0=: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://app.strem.io' is therefore not allowed access. The response had HTTP status code 451. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
js: Failed to load https://stremio-porn.now.sh/stremioget/stremio/v1/q.json?b=eyJwYXJhbXMiOltudWxsLHsicXVlcnkiOnsidHlwZSI6Im1vdmllIn0sImxpbWl0IjoxMDAsInNvcnQiOnsicG9wdWxhcml0aWVzLnBvcm4uUG9ybkNvbSI6LTEsInBvcHVsYXJpdHkiOi0xfX1dLCJtZXRob2QiOiJtZXRhLmZpbmQiLCJpZCI6MSwianNvbnJwYyI6IjIuMCJ9: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://app.strem.io' is therefore not allowed access. The response had HTTP status code 451. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
js: Failed to load https://stremio-porn.now.sh/stremioget/stremio/v1/q.json?b=eyJwYXJhbXMiOltudWxsLHsicXVlcnkiOnsidHlwZSI6InR2In0sImxpbWl0IjoxMDAsInNvcnQiOnsicG9wdWxhcml0aWVzLnBvcm4uQ2hhdHVyYmF0ZSI6LTEsInBvcHVsYXJpdHkiOi0xfX1dLCJtZXRob2QiOiJtZXRhLmZpbmQiLCJpZCI6MSwianNvbnJwYyI6IjIuMCJ9: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://app.strem.io' is therefore not allowed access. The response had HTTP status code 451. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
js: Failed to load https://jlvcm-stremio-mrpiracy.glitch.me/catalog/movie/mr_piracy.json: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://app.strem.io' is therefore not allowed access. The response had HTTP status code 429. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
js: Failed to load https://jlvcm-stremio-mrpiracy.glitch.me/catalog/series/mr_piracy.json: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://app.strem.io' is therefore not allowed access. The response had HTTP status code 429. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
js: Failed to load https://internetarchivestremio.herokuapp.com/stremioget/stremio/v1/q.json?b=eyJwYXJhbXMiOltudWxsLHsicXVlcnkiOnsidHlwZSI6Im1vdmllIn0sImxpbWl0IjoxMDAsInNvcnQiOnsicG9wdWxhcml0aWVzLmludGVybmV0YXJjaGl2ZSI6LTEsInBvcHVsYXJpdHkiOi0xfX1dLCJtZXRob2QiOiJtZXRhLmZpbmQiLCJpZCI6MSwianNvbnJwYyI6IjIuMCJ9: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://app.strem.io' is therefore not allowed access. The response had HTTP status code 404. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
js: Failed to load https://secret-anchorage-23982.herokuapp.com/stremioget/stremio/v1/q.json?b=eyJwYXJhbXMiOltudWxsLHsicXVlcnkiOnsidHlwZSI6ImNoYW5uZWwifSwibGltaXQiOjEwMCwic29ydCI6eyJwb3B1bGFyaXRpZXMuZHR1YmUiOi0xLCJwb3B1bGFyaXR5IjotMX19XSwibWV0aG9kIjoibWV0YS5maW5kIiwiaWQiOjEsImpzb25ycGMiOiIyLjAifQ==: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://app.strem.io' is therefore not allowed access. The response had HTTP status code 503. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
SSDP error: { type: 'ssdp',
  error:
   { type: 'send',
     error:
      { Error: send EPERM 239.255.255.250:1900
          at SendWrap.afterSend [as oncomplete] (dgram.js:467:11)
        errno: 'EPERM',
        code: 'EPERM',
        syscall: 'send',
        address: '239.255.255.250',
        port: 1900 } } }
SSDP error: { type: 'ssdp',
  error:
   { type: 'send',
     error:
      { Error: send EPERM 239.255.255.250:1900
          at SendWrap.afterSend [as oncomplete] (dgram.js:467:11)
        errno: 'EPERM',
        code: 'EPERM',
        syscall: 'send',
        address: '239.255.255.250',
        port: 1900 } } }
SSDP error: { type: 'ssdp',
  error:
   { type: 'send',
     error:
      { Error: send EPERM 239.255.255.250:1900
          at SendWrap.afterSend [as oncomplete] (dgram.js:467:11)
        errno: 'EPERM',
        code: 'EPERM',
        syscall: 'send',
        address: '239.255.255.250',
        port: 1900 } } }
SSDP error: { type: 'ssdp',
  error:
   { type: 'send',
     error:
      { Error: send EPERM 239.255.255.250:1900
          at SendWrap.afterSend [as oncomplete] (dgram.js:467:11)
        errno: 'EPERM',
        code: 'EPERM',
        syscall: 'send',
        address: '239.255.255.250',
        port: 1900 } } }
SSDP error: { type: 'ssdp',
  error:
   { type: 'send',
     error:
      { Error: send EPERM 239.255.255.250:1900
          at SendWrap.afterSend [as oncomplete] (dgram.js:467:11)
        errno: 'EPERM',
        code: 'EPERM',
        syscall: 'send',
        address: '239.255.255.250',
        port: 1900 } } }
SSDP error: { type: 'ssdp',
  error:
   { type: 'send',
     error:
      { Error: send EPERM 239.255.255.250:1900
          at SendWrap.afterSend [as oncomplete] (dgram.js:467:11)
        errno: 'EPERM',
        code: 'EPERM',
        syscall: 'send',
        address: '239.255.255.250',
        port: 1900 } } }
SSDP error: { type: 'ssdp',
  error:
   { type: 'send',
     error:
      { Error: send EPERM 239.255.255.250:1900
          at SendWrap.afterSend [as oncomplete] (dgram.js:467:11)
        errno: 'EPERM',
        code: 'EPERM',
        syscall: 'send',
        address: '239.255.255.250',
        port: 1900 } } }
SSDP error: { type: 'ssdp',
  error:
   { type: 'send',
     error:
      { Error: send EPERM 239.255.255.250:1900
          at SendWrap.afterSend [as oncomplete] (dgram.js:467:11)
        errno: 'EPERM',
        code: 'EPERM',
        syscall: 'send',
        address: '239.255.255.250',
        port: 1900 } } }
SSDP error: { type: 'ssdp',
  error:
   { type: 'send',
     error:
      { Error: send EPERM 239.255.255.250:1900
          at SendWrap.afterSend [as oncomplete] (dgram.js:467:11)
        errno: 'EPERM',
        code: 'EPERM',
        syscall: 'send',
        address: '239.255.255.250',
        port: 1900 } } }
SSDP error: { type: 'ssdp',
  error:
   { type: 'send',
     error:
      { Error: send EPERM 239.255.255.250:1900
          at SendWrap.afterSend [as oncomplete] (dgram.js:467:11)
        errno: 'EPERM',
        code: 'EPERM',
        syscall: 'send',
        address: '239.255.255.250',
        port: 1900 } } }
``

**Comment by vejeta** [comment]
When testing this behaviour by compiling latest stremio-shell, I noticed that in Stremio-shell, the screen is not refreshed until the window is resized.

So I went back to the stable release, and that one exposed the same behaviour.

**Comment by vejeta** [comment]
This seems directly related to stremio, since I am seeing the same behaviour in other apps: chromium, spotify, etc. 

Althought I have not been able to resolve it, it must be a dependant library. Closing for now.

**Comment by Ivshti** [comment]
still, thanks for letting us know!
