### ISSUE TITLE
Stremio streaming server has thrown an error 

### ISSUE THREAD

**Issue by Suburbanno** [Stremio/stremio-bugs#234]
**Describe the bug**
Whenever I try to start a movie, I get this error

**Screenshots**
![image](https://user-images.githubusercontent.com/13632826/86142410-8c1b1780-bac9-11ea-94d7-5304161b7ba9.png)

**Desktop:**
 - OS: [Windows10]
 - Browser: [EDGE]

**Additional context**
```
Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

(node:3980) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
FATAL ERROR: Committing semi space failed. Allocation failed - process out of memory
 1: 00D6785E
 2: 01171903
 3: 01170414
 4: 00F67D35
 5: 0148FD91
(node:9736) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 00D6785E
 2: 00F68661
 3: 0119D635
(node:1916) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
buffer.js:93
    return new ArrayBuffer(size);
           ^

RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at createUnsafeArrayBuffer (buffer.js:93:12)
    at createUnsafeBuffer (buffer.js:87:25)
    at allocate (buffer.js:293:12)
    at Function.Buffer.allocUnsafe (buffer.js:254:10)
    at Function.Buffer.concat (buffer.js:441:23)
    at IncomingMessage.<anonymous> (C:\Users\Vinicius\AppData\Local\Programs\LNV\Stremio-4\server.js:120669:29)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
```

**Comment by tchevri** [comment]
+1
Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

Engine invalid piece 2875 for 8b08a4c2...
Engine invalid piece 2876 for 8b08a4c2...
....
Engine invalid piece 2962 for 8b08a4c2...
Engine invalid piece 2963 for 8b08a4c2...
buffer.js:93
    return new ArrayBuffer(size);
           ^

RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at createUnsafeArrayBuffer (buffer.js:93:12)
    at createUnsafeBuffer (buffer.js:87:25)
    at allocate (buffer.js:293:12)
    at Function.Buffer.allocUnsafe (buffer.js:254:10)
    at Function.Buffer.concat (buffer.js:441:23)
    at PieceBuffer.flush (C:\Users\xxx\AppData\Local\Programs\LNV\Stremio-4\server.js:133517:22)
    at Request.callback (C:\Users\xxx\AppData\Local\Programs\LNV\Stremio-4\server.js:132872:20)
    at Wire._callback (C:\Users\xxx\AppData\Local\Programs\LNV\Stremio-4\server.js:105069:10)
    at Wire._onpiece (C:\Users\xxx\AppData\Local\Programs\LNV\Stremio-4\server.js:105048:7)
    at Wire.onmessage (C:\Users\xxx\AppData\Local\Programs\LNV\Stremio-4\server.js:104860:16)
    at Wire._write (C:\Users\xxx\AppData\Local\Programs\LNV\Stremio-4\server.js:105109:8)
    at doWrite (_stream_writable.js:396:12)
    at writeOrBuffer (_stream_writable.js:382:5)
    at Wire.Writable.write (_stream_writable.js:290:11)
    at Socket.ondata (_stream_readable.js:639:20)

Any suggestion please?
Was never an issue until just a couple of weeks ago...

Settings.json are default:
{
    "appPath": "C:\\Users\\xxx\\AppData\\Roaming\\stremio\\stremio-server",
    "cacheRoot": "D:\\",
    "cacheSize": 10737418240,
    "btMaxConnections": 35,
    "btHandshakeTimeout": 20000,
    "btRequestTimeout": 4000,
    "btDownloadSpeedSoftLimit": 1677721.6,
    "btDownloadSpeedHardLimit": 2621440,
    "btMinPeersForStable": 5,
    "remoteHttps": "",
    "localAddonEnabled": false,
    "serverVersion": "4.11.0",
    "btProfile": "default"
}

tks.

**Comment by tknipe** [comment]
+1
i also get the same error when trying to use Peario addon, which plays stremio media in browser and syncs with friends. When we try and play it plays the audio and subtitle track but no video which is weird. Maybe mine is more to do with the addon as im still able to play media normally on stremio, but the addon hasn't been updated since I last used it so not sure why it would change.

```
Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

Engine invalid piece 0 for 10abfc20867c8bb5bab962847c7bed8f2ac1f822
Engine invalid piece 1 for 10abfc20867c8bb5bab962847c7bed8f2ac1f822
Engine invalid piece 2 for 10abfc20867c8bb5bab962847c7bed8f2ac1f822
Engine invalid piece 3 for 10abfc20867c8bb5bab962847c7bed8f2ac1f822
Engine invalid piece 4 for 10abfc20867c8bb5bab962847c7bed8f2ac1f822
Engine invalid piece 0 for 10abfc20867c8bb5bab962847c7bed8f2ac1f822
Engine invalid piece 1 for 10abfc20867c8bb5bab962847c7bed8f2ac1f822
Engine invalid piece 2 for 10abfc20867c8bb5bab962847c7bed8f2ac1f822
Engine invalid piece 3 for 10abfc20867c8bb5bab962847c7bed8f2ac1f822
Engine invalid piece 4 for 10abfc20867c8bb5bab962847c7bed8f2ac1f822
Engine invalid piece 5 for 10abfc20867c8bb5bab962847c7bed8f2ac1f822
Engine invalid piece 6 for 10abfc20867c8bb5bab962847c7bed8f2ac1f822
Engine invalid piece 7 for 10abfc20867c8bb5bab962847c7bed8f2ac1f822
Engine invalid piece 8 for 10abfc20867c8bb5bab962847c7bed8f2ac1f822
Engine invalid piece 9 for 10abfc20867c8bb5bab962847c7bed8f2ac1f822
Engine invalid piece 10 for 10abfc20867c8bb5bab962847c7bed8f2ac1f822
Engine invalid piece 11 for 10abfc20867c8bb5bab962847c7bed8f2ac1f822
Engine invalid piece 12 for 10abfc20867c8bb5bab962847c7bed8f2ac1f822
Engine invalid piece 13 for 10abfc20867c8bb5bab962847c7bed8f2ac1f822
Engine invalid piece 14 for 10abfc20867c8bb5bab962847c7bed8f2ac1f822
Engine invalid piece 5 for 10abfc20867c8bb5bab962847c7bed8f2ac1f822
Engine invalid piece 6 for 10abfc20867c8bb5bab962847c7bed8f2ac1f822
Engine invalid piece 7 for 10abfc20867c8bb5bab962847c7bed8f2ac1f822
Engine invalid piece 8 for 10abfc20867c8bb5bab962847c7bed8f2ac1f822
Engine invalid piece 9 for 10abfc20867c8bb5bab962847c7bed8f2ac1f822
Engine invalid piece 10 for 10abfc20867c8bb5bab962847c7bed8f2ac1f822
Engine invalid piece 11 for 10abfc20867c8bb5bab962847c7bed8f2ac1f822
Engine invalid piece 12 for 10abfc20867c8bb5bab962847c7bed8f2ac1f822
Engine invalid piece 13 for 10abfc20867c8bb5bab962847c7bed8f2ac1f822
Engine invalid piece 14 for 10abfc20867c8bb5bab962847c7bed8f2ac1f822
C:\Users\xxx\AppData\Local\Programs\LNV\Stremio-4\server.js:95109
		if (this.subBoxNames && this.subBoxNames.indexOf(box.type) != -1) {
		                                                     ^

TypeError: Cannot read property 'type' of undefined
    at BoxParser.ContainerBox.parse (C:\Users\xxx\AppData\Local\Programs\LNV\Stremio-4\server.js:95109:56)
    at Object.BoxParser.parseOneBox (C:\Users\xxx\AppData\Local\Programs\LNV\Stremio-4\server.js:95057:6)
    at ISOFile.parse (C:\Users\xxx\AppData\Local\Programs\LNV\Stremio-4\server.js:97753:20)
    at MP4Box.appendBuffer (C:\Users\xxx\AppData\Local\Programs\LNV\Stremio-4\server.js:98919:20)
    at PassThrough.onData (C:\Users\xxx\AppData\Local\Programs\LNV\Stremio-4\server.js:116074:7)
    at emitOne (events.js:116:13)
    at PassThrough.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at PassThrough.Readable.push (_stream_readable.js:208:10)
    at PassThrough.Transform.push (_stream_transform.js:147:32)
    at PassThrough.afterTransform (_stream_transform.js:88:10)
    at PassThrough._transform (_stream_passthrough.js:42:3)
    at PassThrough.Transform._read (_stream_transform.js:186:10)
    at PassThrough.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:396:12)
```


never had issue before and haven't changed settings. Tried reinstalling stremio, reinstalling addons, using different browsers, so far none worked.

**Comment by Ivshti** [comment]
@core1024 @jaruba any chance this is related to the latest fixes?

**Comment by core1024** [comment]
This is fixed in the latest commits
