### ISSUE TITLE
Remote streaming broken in 4.4.132 latest version for MacOS

### ISSUE THREAD

**Issue by jchlu** [Stremio/stremio-bugs#273]
Since upgrading to the latest version for MacOS, remote streaming fails.

**Screenshots**
The remote browser shows this:
![](https://jchlu.d.pr/nISPQl/KE2F7DXpEe+)

The Stremio instance shows this:
![](https://jchlu.d.pr/fIFkhy/QBkTfNjGJ9+)

with the following full code message:
```javascript
Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

(node:50467) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/Applications/Stremio.app/Contents/MacOS/server.js:118840
	var box = mp4box.createFile();
	                 ^

TypeError: mp4box.createFile is not a function
    at getForMp4 (/Applications/Stremio.app/Contents/MacOS/server.js:118840:19)
    at get (/Applications/Stremio.app/Contents/MacOS/server.js:118699:48)
    at retrieveKeyframesCached (/Applications/Stremio.app/Contents/MacOS/server.js:126844:5)
    at /Applications/Stremio.app/Contents/MacOS/server.js:126792:13
    at /Applications/Stremio.app/Contents/MacOS/server.js:126683:9
    at f (/Applications/Stremio.app/Contents/MacOS/server.js:105667:25)
    at LineStream.<anonymous> (/Applications/Stremio.app/Contents/MacOS/server.js:126740:9)
    at LineStream.emit (events.js:327:22)
    at LineStream.EventEmitter.emit (domain.js:486:12)
    at finish (_stream_writable.js:657:10)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Desktop:**
 - OS: MacOS
 - Browser: Same result on all - Safari, Firefox & Samsung Tizen
 - Version: `4.4.132` / Server: `4.13.0`

**Additional context**
Everything worked perfectly until upgrade to `4.4.132`

**Comment by Ivshti** [comment]
We'll investigate this ASAP, but as a temporary workaround you can donwload 4.4.120 from https://dl.strem.io/shell-osx/v4.4.120/Stremio+4.4.120.dmg

**Comment by jaruba** [comment]
@jchlu Can you give us some more information about this?

- What OSX device are you using? 
- What OSX version are you using?
- How are you using Stremio?
- What are you streaming to? Exact device and any other relevant data that you can think of.

We are trying to reproduce your issue but have been unable to do yet.

**Comment by jchlu** [comment]
![](https://jchlu.d.pr/7IXxre/qFeevjTS3L+)

Normally streaming from this to a Samsung TizenOS TV browser locally on the same Wifi network, but tested to other devices with the same result. (Another MacBook Pro on the same wifi network).
I can browse / search for shows, choose episodes and then the initial progress bar loads - the failure occurs once it attempts to play.
Both the normal local `http://` with the local IP address and port, and the "remote https" URL fail in the exact same way.

**Comment by jchlu** [comment]
*UPDATE:* 
Downgrading as per [your suggestion](https://github.com/Stremio/stremio-bugs/issues/273#issuecomment-802922714) works perfectly, over both `http` & `https` to the other MacBook & the Tizen Browser on the TV.

**Comment by jchlu** [comment]
@jaruba Why was this report closed? Is there a fix?

**Comment by TRtomasz** [comment]
@jchlu  it was automatically closed as we merged fix to our code base. But is has not been released yet
