### ISSUE TITLE
Array buffer allocation failed

### ISSUE THREAD

**Issue by seahindeniz** [Stremio/stremio-bugs#300]
**Describe the bug**
While watching the Katla season 1, episode 1, I get `Array buffer allocation failed` error

<details>
<summary>Here is the output</summary>
Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

(node:30404) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `stremio-runtime --trace-deprecation ...` to show where the warning was created)
internal/buffer.js:951
class FastBuffer extends Uint8Array {}
^

RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at new FastBuffer (internal/buffer.js:951:1)
    at Function.alloc (buffer.js:378:10)
    at Object.read (C:\Users\Sahin\AppData\Local\Programs\LNV\Stremio-4\server.js:137620:24)
    at C:\Users\Sahin\AppData\Local\Programs\LNV\Stremio-4\server.js:137506:9
    at C:\Users\Sahin\AppData\Local\Programs\LNV\Stremio-4\server.js:7852:20
    at Object.async.forEachOf.async.eachOf (C:\Users\Sahin\AppData\Local\Programs\LNV\Stremio-4\server.js:7904:13)
    at Object.async.forEach.async.each (C:\Users\Sahin\AppData\Local\Programs\LNV\Stremio-4\server.js:7880:22)
    at that.read (C:\Users\Sahin\AppData\Local\Programs\LNV\Stremio-4\server.js:137495:9)
    at Timeout._onTimeout (C:\Users\Sahin\AppData\Local\Programs\LNV\Stremio-4\server.js:9098:34)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:33680) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `stremio-runtime --trace-deprecation ...` to show where the warning was created)
internal/buffer.js:951
class FastBuffer extends Uint8Array {}
^

RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at new FastBuffer (internal/buffer.js:951:1)
    at Function.alloc (buffer.js:378:10)
    at Object.read (C:\Users\Sahin\AppData\Local\Programs\LNV\Stremio-4\server.js:137620:24)
    at C:\Users\Sahin\AppData\Local\Programs\LNV\Stremio-4\server.js:137506:9
    at C:\Users\Sahin\AppData\Local\Programs\LNV\Stremio-4\server.js:7852:20
    at Object.async.forEachOf.async.eachOf (C:\Users\Sahin\AppData\Local\Programs\LNV\Stremio-4\server.js:7904:13)
    at Object.async.forEach.async.each (C:\Users\Sahin\AppData\Local\Programs\LNV\Stremio-4\server.js:7880:22)
    at that.read (C:\Users\Sahin\AppData\Local\Programs\LNV\Stremio-4\server.js:137495:9)
    at Timeout._onTimeout (C:\Users\Sahin\AppData\Local\Programs\LNV\Stremio-4\server.js:9098:34)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:33808) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `stremio-runtime --trace-deprecation ...` to show where the warning was created)
internal/buffer.js:951
class FastBuffer extends Uint8Array {}
^

RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at new FastBuffer (internal/buffer.js:951:1)
    at Function.alloc (buffer.js:378:10)
    at Object.read (C:\Users\Sahin\AppData\Local\Programs\LNV\Stremio-4\server.js:137620:24)
    at C:\Users\Sahin\AppData\Local\Programs\LNV\Stremio-4\server.js:137506:9
    at C:\Users\Sahin\AppData\Local\Programs\LNV\Stremio-4\server.js:7852:20
    at Object.async.forEachOf.async.eachOf (C:\Users\Sahin\AppData\Local\Programs\LNV\Stremio-4\server.js:7904:13)
    at Object.async.forEach.async.each (C:\Users\Sahin\AppData\Local\Programs\LNV\Stremio-4\server.js:7880:22)
    at that.read (C:\Users\Sahin\AppData\Local\Programs\LNV\Stremio-4\server.js:137495:9)
    at Timeout._onTimeout (C:\Users\Sahin\AppData\Local\Programs\LNV\Stremio-4\server.js:9098:34)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
</details>

**To Reproduce**
1. Choose this source 
![image](https://user-images.githubusercontent.com/5789670/122478689-86685b80-cfd2-11eb-8ce1-53bfc827ba1d.png)

2. Watch it like 5 minutes or something
3. Expect the error

**Expected behavior**
Well, no errors 🙂

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 4.4.137

**Comment by jaruba** [comment]
I checked and there is nothing wrong with that stream, the `Array buffer allocation failed` error shows when you run out of RAM. It happens can happen more frequently if there is [torrent poisoning](https://en.wikipedia.org/wiki/Torrent_poisoning). Although this torrent does not appear to be poisoned now, it may have been when you attempted to stream it.

**Comment by seahindeniz** [comment]
I have 24gb ram and I mostly work on 50% of it on a regular day and when I watch something, it regularly is around 35% of the 24gb RAM, so I definitely get against that is the reason actually 🤔 Since I was also watching it normally, and you also confirmed that there is nothing wrong with the torrent so, I think it's also out of scope here

**Comment by jaruba** [comment]
@seahindeniz That's a lot of RAM, but keep in mind that Stremio is a 32bit app on Windows. 32bit apps can only use a maximum of 4GB of RAM. We've only ever seen that error for Windows users though, and it's usually in combination with torrent poisoning.

**Comment by seahindeniz** [comment]
Hmm. Do you have any plans for releasing a 64-bit version of Stremio?

**Comment by jaruba** [comment]
We do have some issues with releasing a 64bit version. There can be bugs that happen in 64bit only and not 32bit (or vice versa) so it would presume dedicating more development time to having such a release.

To note, while 32bit versions work on both 32bit and 64bit architectures on Windows, 64bit would work only on 64bit architectures.

We'd rather fix the underlying issues that are caused from torrent poisoning than release a 64bit version tbh, but if issues keep happening with the 32bit we might consider releasing a 64bit version too.
