### ISSUE TITLE
Casting fails with error on 3 different OS

### ISSUE THREAD

**Issue by Lywel** [Stremio/stremio-bugs#327]
**Describe the bug**
Casting throws an error from 3 different OS.

**To Reproduce**
1. Start a stream
2. Click the cast button
3. Select the device to cast on

**Expected behavior**
It should cast without an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/7943389/143307182-4bc629a8-279b-4fc3-8dcf-027d351de69d.png)

**Desktop (please complete the following information):**
 - OS: MacOs, Archlinux, Windows
 - Browser: not using a browser
 - Stremio version: 4.4.142
 - Server: 4.18.0

**Additional context**

Here is the error, paths are obviously different between the 3 OS I tried from but it's the same Warning and error pattern.
```
Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

(node:13336) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/Applications/Stremio.app/Contents/MacOS/server.js:44126
  throw err;
  ^

Error: Invalid character in entity name
Line: 0
Column: 1390
Char: =
    at error (/Applications/Stremio.app/Contents/MacOS/server.js:45030:10)
    at strictFail (/Applications/Stremio.app/Contents/MacOS/server.js:45056:7)
    at SAXParser.write (/Applications/Stremio.app/Contents/MacOS/server.js:45855:13)
    at XMLParser.feed (/Applications/Stremio.app/Contents/MacOS/server.js:44130:15)
    at ElementTree.parse (/Applications/Stremio.app/Contents/MacOS/server.js:43669:10)
    at Object.parse (/Applications/Stremio.app/Contents/MacOS/server.js:43982:8)
    at /Applications/Stremio.app/Contents/MacOS/server.js:141552:22
    at ConcatStream.<anonymous> (/Applications/Stremio.app/Contents/MacOS/server.js:36631:43)
    at ConcatStream.emit (events.js:327:22)
    at ConcatStream.EventEmitter.emit (domain.js:486:12)
    at finishMaybe (/Applications/Stremio.app/Contents/MacOS/server.js:38380:14)
    at afterWrite (/Applications/Stremio.app/Contents/MacOS/server.js:38266:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Comment by TRtomasz** [comment]
Hi, did you try casting to a chromecast/android tv or it was other kind of device?
If that was just regular TV, dlna casting is no longer supported.

**Comment by Lywel** [comment]
Thanks for your answer.

> If that was just regular TV, dlna casting is no longer supported.

Yeah it's an old set top box. If dlna is no longer supported that explains it.

I would be nice to have a better error handling, it's not my stremio setup that is wrong, but the client that is outdated/incompatible.
