### ISSUE TITLE
Can't play with MPV on Linux (subtitles)

### ISSUE THREAD

**Issue by Darkmaster006** [Stremio/stremio-bugs#335]
**Describe the bug**
When I choose 'play with MPV', there's an error. If I disable the subtitles, though, it does work correctly. (I also want to report the subtitles are not correctly aligned to the audio, is this the torrent's fault?)

**To Reproduce**
1. Start a movie from a magnet link.
2. Click on play with MPV.
3. See error

**Expected behavior**
Playing in MPV with subtitles.

**Screenshots**
Log:
Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

{ Error: listen EADDRINUSE: address already in use :::11470
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Object.require.720../cache (/opt/stremio/server.js:134000:8)
    at s (/opt/stremio/server.js:1:338)
    at e (/opt/stremio/server.js:1:509)
    at Object.<anonymous> (/opt/stremio/server.js:1:527)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 11470 }
{ Error: listen EADDRINUSE: address already in use :::12470
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Object.require.720../cache (/opt/stremio/server.js:134022:9)
    at s (/opt/stremio/server.js:1:338)
    at e (/opt/stremio/server.js:1:509)
    at Object.<anonymous> (/opt/stremio/server.js:1:527)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 12470 }
fs.js:114
    throw err;
    ^

Error: EACCES: permission denied, open '/opt/stremio/../../subtitles.srt'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at IncomingMessage.<anonymous> (/opt/stremio/server.js:133661:36)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
{ Error: listen EADDRINUSE: address already in use :::11470
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Object.require.720../cache (/opt/stremio/server.js:134000:8)
    at s (/opt/stremio/server.js:1:338)
    at e (/opt/stremio/server.js:1:509)
    at Object.<anonymous> (/opt/stremio/server.js:1:527)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 11470 }
{ Error: listen EADDRINUSE: address already in use :::12470
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Object.require.720../cache (/opt/stremio/server.js:134022:9)
    at s (/opt/stremio/server.js:1:338)
    at e (/opt/stremio/server.js:1:509)
    at Object.<anonymous> (/opt/stremio/server.js:1:527)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 12470 }
fs.js:114
    throw err;
    ^

Error: EACCES: permission denied, open '/opt/stremio/../../subtitles.srt'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at IncomingMessage.<anonymous> (/opt/stremio/server.js:133661:36)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.2
 - Firefox
 - 94.0

Seems like this was also reported here: https://github.com/Stremio/stremio-bugs/issues/289

**Comment by TRtomasz** [comment]
This issue has been fixed, please update stremio to the latest version

**Comment by Darkmaster006** [comment]
> This issue has been fixed, please update stremio to the latest version

As far as I know, I have the latest version. I'll uninstall all and reinstall from scratch from the .deb from the page, see how it goes, and I'll let you know. Thanks for the help!

**Comment by Darkmaster006** [comment]
> This issue has been fixed, please update stremio to the latest version

Well, this seems to have fixed itself alone (or rather, I'd uploaded and the bug seemed to still be there, but it wasn't). Thank you for the help, I'll close this now.
