### ISSUE TITLE
Streaming server not opening/Streaming engine not connected or an old version

### ISSUE THREAD

**Issue by victorgveloso** [Stremio/stremio-bugs#358]
**Describe the bug**

"Show Details" button pops up a long text block with the following information:
```
Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

(node:14896) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `stremio-runtime --trace-deprecation ...` to show where the warning was created)
TypeError: WebSocket is not a constructor
    at new Socket (C:\Users\victor\AppData\Local\Programs\LNV\Stremio-4\server.js:125072:14)
    at WebSocketTracker._openSocket (C:\Users\victor\AppData\Local\Programs\LNV\Stremio-4\server.js:11903:50)
    at new WebSocketTracker (C:\Users\victor\AppData\Local\Programs\LNV\Stremio-4\server.js:11827:8)
    at C:\Users\victor\AppData\Local\Programs\LNV\Stremio-4\server.js:11115:16
    at Array.map (<anonymous>)
    at new Client (C:\Users\victor\AppData\Local\Programs\LNV\Stremio-4\server.js:11107:6)
    at Tracker.run (C:\Users\victor\AppData\Local\Programs\LNV\Stremio-4\server.js:106908:22)
    at C:\Users\victor\AppData\Local\Programs\LNV\Stremio-4\server.js:106847:5
    at Array.forEach (<anonymous>)
    at peerSearch.run (C:\Users\victor\AppData\Local\Programs\LNV\Stremio-4\server.js:106844:48)
    at new peerSearch (C:\Users\victor\AppData\Local\Programs\LNV\Stremio-4\server.js:106866:7)
    at createEngine (C:\Users\victor\AppData\Local\Programs\LNV\Stremio-4\server.js:45009:38)
    at C:\Users\victor\AppData\Local\Programs\LNV\Stremio-4\server.js:45170:5
    at Layer.handle [as handle_request] (C:\Users\victor\AppData\Local\Programs\LNV\Stremio-4\server.js:121116:5)
    at next (C:\Users\victor\AppData\Local\Programs\LNV\Stremio-4\server.js:121349:13)
    at Route.dispatch (C:\Users\victor\AppData\Local\Programs\LNV\Stremio-4\server.js:121314:3)
_http_outgoing.js:558
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:558:11)
    at ServerResponse.writeHead (_http_server.js:289:21)
    at C:\Users\victor\AppData\Local\Programs\LNV\Stremio-4\server.js:45171:13
    at EventEmitter.<anonymous> (C:\Users\victor\AppData\Local\Programs\LNV\Stremio-4\server.js:44993:58)
    at Object.onceWrapper (events.js:422:26)
    at EventEmitter.emit (events.js:327:22)
    at EventEmitter.emit (domain.js:486:12)
    at C:\Users\victor\AppData\Local\Programs\LNV\Stremio-4\server.js:45024:35
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```
**To Reproduce**
1. Install Brazuca Addon;
2. Search for Attack on Titans;
3. Open episode 23 from the fourth season;
4. See error.

**Expected behavior**
The streaming should run without problems.

**Screenshots**

![Brazuca Failing](https://user-images.githubusercontent.com/11022419/155900996-23e09880-ba26-495d-875d-b30017c9045b.png)

![Brazuca Failing2](https://user-images.githubusercontent.com/11022419/155901175-6add50df-c022-49f6-a343-17b980cd8836.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Version latest (I tried to reinstall stremio and disabled/enabled all my addons)

**Additional context**
Brazuca is not the only affected addon, but I know TorrentIO works.

**Comment by TRtomasz** [comment]
@core1024  this reproducible but only in the production version, couldn't reproduce it with local server. Any chance we have fixed it?

**Comment by BrettS420** [comment]
Same issue.
