### ISSUE TITLE
Stremio has problems in starting its streaming server

### ISSUE THREAD

**Issue by realmandal** [Stremio/stremio-bugs#383]
### Issue:
Whenever i play any video through either an addon or magnet links it plays on my laptop without any problems. But as soon as i cast it to my tv, it pops an error message that says the "Stremio streaming server can't be started" and has extra details underneath. I will be attaching the screenshots and the error messages that popped below.

I am currently on an m1 mac and even today in the morning the Stremio cast feature worked. 

### Steps to reproduce the error : 
1. Play any video on stremio app for mac
2. Cast it to any tv.
3. Use cmd+q to quit the stremio app on mac while its casting 
4. Re open the stremio app and play any video and then cast again

I had opened a firefox tab and stremio together but while i was casting to the tv using stremio i accidentaly used 'cmd+q' to quit stremio instead of firefox.
so I once again opened stremio to cast again and then the problem started.

### Device Properties:
 - OS: macOS Monterey v12.4
 - Browser Firefox

### Things i have already tried to solve this issue:
1. I have uninstalled and then reinstalled stremio(version 4.4 beta for macOS High Sierra and above)
2. Restarted my mac3. 
3. Cleared the cache for stremio in the ```~/Library/caches/stremio``` folder

### The pop up screenshot along with the error message:
<img width="1342" alt="Screenshot 2022-06-26 at 7 16 39 PM" src="https://user-images.githubusercontent.com/69709719/175817567-ccd3f189-316f-4b09-bb2b-b7ee90c03459.png">

**When i click on the show details it pops this section and this text is shown :** 
```Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

(node:71367) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error: listen EADDRINUSE: address already in use :::11470
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at Object.require.727../cache (/Applications/Stremio.app/Contents/MacOS/server.js:135065:8)
    at s (/Applications/Stremio.app/Contents/MacOS/server.js:1:338)
    at e (/Applications/Stremio.app/Contents/MacOS/server.js:1:509)
    at Object.<anonymous> (/Applications/Stremio.app/Contents/MacOS/server.js:1:527)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 11470
}
Error: listen EADDRINUSE: address already in use :::12470
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at Object.require.727../cache (/Applications/Stremio.app/Contents/MacOS/server.js:135087:9)
    at s (/Applications/Stremio.app/Contents/MacOS/server.js:1:338)
    at e (/Applications/Stremio.app/Contents/MacOS/server.js:1:509)
    at Object.<anonymous> (/Applications/Stremio.app/Contents/MacOS/server.js:1:527)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 12470
}
/Applications/Stremio.app/Contents/MacOS/server.js:44126
  throw err;
  ^

Error: Invalid character in entity name
Line: 0
Column: 239
Char: =
    at error (/Applications/Stremio.app/Contents/MacOS/server.js:45030:10)
    at strictFail (/Applications/Stremio.app/Contents/MacOS/server.js:45056:7)
    at SAXParser.write (/Applications/Stremio.app/Contents/MacOS/server.js:45855:13)
    at XMLParser.feed (/Applications/Stremio.app/Contents/MacOS/server.js:44130:15)
    at ElementTree.parse (/Applications/Stremio.app/Contents/MacOS/server.js:43669:10)
    at Object.parse (/Applications/Stremio.app/Contents/MacOS/server.js:43982:8)
    at parseEvents (/Applications/Stremio.app/Contents/MacOS/server.js:141821:14)
    at /Applications/Stremio.app/Contents/MacOS/server.js:141758:22
    at ConcatStream.<anonymous> (/Applications/Stremio.app/Contents/MacOS/server.js:36631:43)
    at ConcatStream.emit (events.js:327:22)
    at ConcatStream.EventEmitter.emit (domain.js:486:12)
    at finishMaybe (/Applications/Stremio.app/Contents/MacOS/server.js:38380:14)
    at endWritable (/Applications/Stremio.app/Contents/MacOS/server.js:38390:3)
    at ConcatStream.Writable.end (/Applications/Stremio.app/Contents/MacOS/server.js:38360:41)
    at IncomingMessage.onend (_stream_readable.js:684:10)
    at Object.onceWrapper (events.js:421:28)
```

**Comment by TRtomasz** [comment]
Only casting to a chromecast is supported, it looks like you are trying to cast to not a chromecast device, in other words DLNA device. DLNA casting is no longer supported.

**Comment by realmandal** [comment]
Yeah, that maybe the problem. But i still didn't get if DLNA is not supported how did it work on the morning of the day this error first occurred. 
It happened as soon as i used cmd+q to quit stremio while the stream was going on.
