### ISSUE TITLE
Server stopped working every time after only a few seconds of watching anything

### ISSUE THREAD

**Issue by chrisafl** [Stremio/stremio-bugs#445]
**Describe the bug**
I am using Stremio for Windows, and every time I watch something the "Streaming server has thrown an error" after a few seconds of watching. Playback still continues but after that point I lose the ability to scrub and my progress in a video is not saved.

I suspect this has something to do with some missing or invalid data in stremio-server\server-settings.json.

I used to get a similar error every time I watched something after a few seconds because that file was missing. Finally I fiddled with server settings and that was enough to get stremio to create that file. The error now still refers to an unexpected end of JSON input, and I'm guessing it is referring to something missing in that same file.

**To Reproduce**
Open stremio, watch something

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Not watching in browser, but I have Edge and Chrome and Firefox

**Additional context**

Contents of server-settings.json:

{
    "serverVersion": "4.19.0",
    "appPath": "C:\\Users\\Chris\\AppData\\Roaming\\stremio\\stremio-server",
    "cacheRoot": "C:\\Users\\Chris\\AppData\\Roaming\\stremio\\stremio-server",
    "cacheSize": 2147483648,
    "btMaxConnections": 55,
    "btHandshakeTimeout": 20000,
    "btRequestTimeout": 4000,
    "btDownloadSpeedSoftLimit": 2621440,
    "btDownloadSpeedHardLimit": 3670016,
    "btMinPeersForStable": 5,
    "remoteHttps": "",
    "localAddonEnabled": false,
    "btProfile": "default"
}

Full error log generated by Stremio:

Stremio streaming server has thrown an error 
QProcess::ProcessError code: 134

Cannot update settings Unexpected end of JSON input
(node:42948) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `stremio-runtime --trace-deprecation ...` to show where the warning was created)

<--- Last few GCs --->

[42948:03C4ACA8]    76362 ms: Scavenge 24.8 (27.5) -> 24.8 (27.5) MB, 0.1 / 0.0 ms  (average mu = 0.812, current mu = 0.000) external memory pressure 
[42948:03C4ACA8]    76407 ms: Mark-sweep 24.8 (27.5) -> 24.3 (27.1) MB, 21.0 / 0.0 ms  (+ 22.1 ms in 99 steps since start of marking, biggest step 3.2 ms, walltime since start of marking 52 ms) (average mu = 0.925, current mu = 0.953) finalize incremental

<--- JS stacktrace --->

FATAL ERROR: Zone Allocation failed - process out of memory
Cannot update settings Unexpected end of JSON input
(node:32284) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `stremio-runtime --trace-deprecation ...` to show where the warning was created)

<--- Last few GCs --->

[32284:03C1AC58]  1821977 ms: Mark-sweep 25.5 (29.0) -> 24.6 (29.6) MB, 1.5 / 0.0 ms  (+ 4.6 ms in 35 steps since start of marking, biggest step 0.2 ms, walltime since start of marking 12 ms) (average mu = 0.871, current mu = 0.912) finalize incremental m[32284:03C1AC58]  1822021 ms: Scavenge 24.8 (29.6) -> 24.6 (29.6) MB, 0.1 / 0.0 ms  (average mu = 0.871, current mu = 0.912) external memory pressure 

<--- JS stacktrace --->

FATAL ERROR: Zone Allocation failed - process out of memory

**Comment by TRtomasz** [comment]
Hi, thanks for your report, could you please check the following things
1. If you have any enviroment variables set that could affect node default settings like `NODE_OPTIONS`
2. Do you have any antivirus software running that might force some apps run in a sandbox? Or any antivirus software installed
3. Could you please try do the following
- Set Environemt variable, like on screenshots with `NODE_OPTIONS` in name and `--inspect` in value
![image](https://user-images.githubusercontent.com/40594253/222149630-2db826da-954b-41d7-878f-cdac36692183.png)
![image](https://user-images.githubusercontent.com/40594253/222149962-26632972-45f8-4793-8628-2f0a84b4b6b1.png)
4. Start stremio again, and then open chrome and press f12 buttom, and click this icon 
![image](https://user-images.githubusercontent.com/40594253/222150253-70100c06-fe6f-4034-86c4-0e299ffa7c84.png)
5. Wait for crash to happen and then follow instruction from first method described here https://nodejs.org/en/docs/guides/diagnostics/memory/using-heap-snapshot/ and send us this file.

**Comment by TRtomasz** [comment]
closing due to lack of activity

**Comment by FunkeCoder23** [comment]
I have the same error
```
Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

(node:20212) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `stremio-runtime --trace-deprecation ...` to show where the warning was created)

<--- Last few GCs --->

[20212:009170D0]    66922 ms: Scavenge 24.5 (27.6) -> 24.5 (27.6) MB, 0.2 / 0.0 ms  (average mu = 0.923, current mu = 0.002) external memory pressure 
[20212:009170D0]    66926 ms: Mark-sweep 24.5 (27.6) -> 24.1 (27.1) MB, 0.3 / 0.0 ms  (+ 4.3 ms in 28 steps since start of marking, biggest step 0.2 ms, walltime since start of marking 9 ms) (average mu = 0.962, current mu = 0.979) finalize incremental ma

<--- JS stacktrace --->

FATAL ERROR: Zone Allocation failed - process out of memory
(node:2368) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `stremio-runtime --trace-deprecation ...` to show where the warning was created)

<--- Last few GCs --->

[2368:04845750]  2601078 ms: Scavenge 24.7 (27.8) -> 24.7 (27.8) MB, 0.2 / 0.0 ms  (average mu = 0.906, current mu = 0.001) external memory pressure 
[2368:04845750]  2601084 ms: Mark-sweep 24.7 (27.8) -> 24.2 (27.4) MB, 0.4 / 0.0 ms  (+ 3.7 ms in 27 steps since start of marking, biggest step 0.3 ms, walltime since start of marking 6 ms) (average mu = 0.958, current mu = 0.981) finalize incremental mar

<--- JS stacktrace --->

FATAL ERROR: Zone Allocation failed - process out of memory
(node:14428) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `stremio-runtime --trace-deprecation ...` to show where the warning was created)
internal/buffer.js:951
class FastBuffer extends Uint8Array {}
^
```

and with the `NODE_OPTIONS` set to `--inspect`` I get the additional:
```
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at new FastBuffer (internal/buffer.js:951:1)
    at createUnsafeBuffer (buffer.js:152:12)
    at allocate (buffer.js:422:10)
    at Function.allocUnsafe (buffer.js:387:10)
    at Function.concat (buffer.js:567:25)
    at IncomingMessage.<anonymous> (C:\Users\*****\AppData\Local\Programs\LNV\Stremio-4\server.js:18332:35)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:486:12)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by TRtomasz** [comment]
@FunkeCoder23  looks like you are running out of ram?

**Comment by FunkeCoder23** [comment]
Seems highly unlikely. The machine has 32GB and not much runs on it. Unless there's a stremio self-limitation on how much RAM it uses?

**Comment by TRtomasz** [comment]
@FunkeCoder23  you could try increasing node max memory like this `--max-old-space-size=8192` but even default limit should be enough.

**Comment by FunkeCoder23** [comment]
> @FunkeCoder23 you could try increasing node max memory like this `--max-old-space-size=8192` but even default limit should be enough.

So that actually instantly crashes Stremio Server 🙃 

```
Stremio streaming server has thrown an error 
QProcess::ProcessError code: 134

Debugger listening on ws://127.0.0.1:9229/2a08590d-b15d-479b-86d6-76de37ae2836
For help, see: https://nodejs.org/en/docs/inspector

<--- Last few GCs --->

[16744:03DA5F08]       38 ms: Mark-sweep 0.9 (3.3) -> 0.9 (3.3) MB, 0.5 / 0.0 ms  (average mu = 0.894, current mu = 0.017) allocation failure scavenge might not succeed
[16744:03DA5F08]       38 ms: Mark-sweep (reduce) 0.9 (3.3) -> 0.9 (3.3) MB, 0.6 / 0.0 ms  (average mu = 0.822, current mu = 0.016) last resort GC in old space requested
[16744:03DA5F08]       39 ms: Mark-sweep (reduce) 0.9 (2.3) -> 0.9 (3.3) MB, 0.7 / 0.0 ms  (average mu = 0.702, current mu = 0.010) last resort GC in old space requested


<--- JS stacktrace --->

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

**Comment by FunkeCoder23** [comment]
(Without the `max-old-space-size change`) I've been watching the processes, the server will always balloon up to 1.5GB RAM and then die. I'm not sure if that RAM usage is expected, or why it dies at 1.5GB

**Comment by FunkeCoder23** [comment]
I've noticed that the stremio-runtime seems to have increased network activity when faulty, and stremio.exe has the activity when working properly.
![image](https://github.com/Stremio/stremio-bugs/assets/12570656/bee2b82c-a188-4126-80f9-55c9af5f2b56)
the 500Mbps is network activity
