### ISSUE TITLE
Casting to Android TV crashes with `cannot read property 'send' of null`

### ISSUE THREAD

**Issue by IceWreck** [Stremio/stremio-bugs#471]
**Describe the bug**
Casting stream to TV is broken.

**To Reproduce**
1. Play a video and wait till it starts playing
2. Click the cast button and choose TV's name
3. There is an error in stremio terminal logs and stremio on desktop shows the "slow loading I give up screen". TV just shows a black screen.

**Expected behavior**
Casts video to TV

**Logs**
```
-> GET /casting
-> GET /opensubHash?videoUrl=http%3A%2F%2F127.0.0.1%3A11470%2F8804b1cead4b13817a6b516c28ce61302a131d39%2F1
-> HEAD /8804b1cead4b13817a6b516c28ce61302a131d39/1
-> GET /8804b1cead4b13817a6b516c28ce61302a131d39/1 bytes=0-65535
-> GET /8804b1cead4b13817a6b516c28ce61302a131d39/1 bytes=2366778750-2366844285
-> OPTIONS /casting/e6a60581-f638-f36e-0ecc-2c59e5bc5ef0/player
-> POST /casting/e6a60581-f638-f36e-0ecc-2c59e5bc5ef0/player
-> POST /casting/e6a60581-f638-f36e-0ecc-2c59e5bc5ef0/player
TypeError: Cannot read property 'send' of null
at Client.send (/app/opt/stremio/server.js:77230:17)
at ChromecastClient.request (/app/opt/stremio/server.js:76999:21)
at ChromecastClient._disconnect (/app/opt/stremio/server.js:77021:37)
at ChromecastClient._connect (/app/opt/stremio/server.js:77028:20)
at ChromecastClient.init (/app/opt/stremio/server.js:77064:51)
at ChromecastClient.Player.methodInvoke (/app/opt/stremio/server.js:33987:21)
at ChromecastClient.Player.middleware (/app/opt/stremio/server.js:34014:23)
at ChromecastClient.middleware (/app/opt/stremio/server.js:77095:37)
at /app/opt/stremio/server.js:73067:58
at Layer.handle_request (/app/opt/stremio/server.js:17513:13)
at next (/app/opt/stremio/server.js:46473:67)
at Route.dispatch (/app/opt/stremio/server.js:46474:11)
at /app/opt/stremio/server.js:9388:19
at Layer.handle_request (/app/opt/stremio/server.js:17513:13)
at /app/opt/stremio/server.js:9300:74
at param (/app/opt/stremio/server.js:9341:57)
```

**Device**
TV: Android 11
Stremio Device: Fedora Linux with Flatpak stremio 
![image](https://github.com/Stremio/stremio-bugs/assets/18102790/bff4035f-89e3-4185-b08c-507d6dd8a16f)

**Comment by TRtomasz** [comment]
Sorry about the issue but you can install Stremio directly on your Android TV and play something without casting.

**Comment by TRtomasz** [comment]
Closing this issue as we have released new app version https://blog.stremio.com/stremio-5-released-for-linux/
