### ISSUE TITLE
Error - Stremio streaming server has thrown an error

### ISSUE THREAD

**Issue by ViniciusFXavier** [Stremio/stremio-bugs#480]
**Describe the bug**
I was watching a movie `Flash` and I got this error.

**Screenshots**
![Sem título](https://github.com/Stremio/stremio-core/assets/40774281/bda610e8-e33c-4a1c-b52b-a6412901233a)

**Error**
```
Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

(node:2732) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `stremio-runtime --trace-deprecation ...` to show where the warning was created)
```

**Desktop (please complete the following information):**
![image](https://github.com/Stremio/stremio-core/assets/40774281/841344fa-2142-439c-9d57-b358fa4ceede)

**Comment by ViniciusFXavier** [comment]
https://github.com/Stremio/stremio-core/issues/485

**Comment by jaruba** [comment]
@ViniciusFXavier how much disk space do u have on ur main drive (where Windows is installed), were u trying to watch a large 4k file through torrent streaming?

the server usually crashes when u run out of disk space

**Comment by ViniciusFXavier** [comment]
> @ViniciusFXavier how much disk space do u have on ur main drive (where Windows is installed), were u trying to watch a large 4k file through torrent streaming?
> 
> the server usually crashes when u run out of disk space

I believe the problem is not space, I have 75Gb free disk space.
I usually watch 1080p.

**Comment by TheSparrowLenz** [comment]
Same issue. Happens mostly when starting a stream and immediately pausing it, after a while the error pops up but the stream can be played.

`Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

(node:15516) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `stremio-runtime --trace-deprecation ...` to show where the warning was created)
internal/buffer.js:951
class FastBuffer extends Uint8Array {}
^

RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at new FastBuffer (internal/buffer.js:951:1)
    at Function.alloc (buffer.js:378:10)
    at Object.read (C:\Users\x_\AppData\Local\Programs\LNV\Stremio-4\server.js:63087:52)
    at C:\Users\x_\AppData\Local\Programs\LNV\Stremio-4\server.js:63111:22
    at C:\Users\x_\AppData\Local\Programs\LNV\Stremio-4\server.js:6769:24
    at Object.async.forEachOf.async.eachOf (C:\Users\x_\AppData\Local\Programs\LNV\Stremio-4\server.js:7010:13)
    at Object.async.forEach.async.each (C:\Users\x_\AppData\Local\Programs\LNV\Stremio-4\server.js:7002:26)
    at that.read (C:\Users\x_\AppData\Local\Programs\LNV\Stremio-4\server.js:63106:19)
    at Timeout._onTimeout (C:\Users\x_\AppData\Local\Programs\LNV\Stremio-4\server.js:62920:20)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
`

**Comment by kKaskak** [comment]
please try the newest v5 beta version
