### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by vinsalmont** [Stremio/stremio-bugs#54]
Uncaught Exception:
TypeError: value is out of bounds
    at checkInt (buffer.js:792:11)
    at Buffer.writeUInt32BE (buffer.js:881:5)
    at Wire._message (/Applications/Stremio.app/Contents/Resources/app.asar/node_modules/torrent-stream/node_modules/peer-wire-swarm/node_modules/peer-wire-protocol/index.js:330:10)
    at Wire.request (/Applications/Stremio.app/Contents/Resources/app.asar/node_modules/torrent-stream/node_modules/peer-wire-swarm/node_modules/peer-wire-protocol/index.js:189:7)
    at m (/Applications/Stremio.app/Contents/Resources/app.asar/node_modules/torrent-stream/index.js:1:2518)
    at A (/Applications/Stremio.app/Contents/Resources/app.asar/node_modules/torrent-stream/index.js:1:5691)
    at U (/Applications/Stremio.app/Contents/Resources/app.asar/node_modules/torrent-stream/index.js:1:6055)
    at K (/Applications/Stremio.app/Contents/Resources/app.asar/node_modules/torrent-stream/index.js:1:6948)
    at Array.forEach (native)
    at N (/Applications/Stremio.app/Contents/Resources/app.asar/node_modules/torrent-stream/index.js:1:6969)

**Comment by Loopiezlol** [comment]
also for me
