### ISSUE TITLE
Crashing stremio on Android TV when loading larger poster image from Add-on

### ISSUE THREAD

**Issue by mhdzumair** [Stremio/stremio-bugs#575]
**Describe the bug**
I developed a streamio add-on [MediaFusion](https://882b9915d0fe-mediafusion.baby-beamup.club). Several users are complaining that, when they try to use my add-on on Chromecast / Android TV it get crash, but the add-on perfectly working in pcs and mobile device application. 

**To Reproduce**
1. Install [MediaFusion](https://882b9915d0fe-mediafusion.baby-beamup.club) Add-on
2. Scroll the available movies
3. Stremio will get crashed evantually. (not all posters, im not able to find out which poster that makes error)

**Expected behavior**
I'm awear that `poster` should be lower than 100Kb according to the add-on [documentation](https://github.com/Stremio/stremio-addon-sdk/blob/master/docs/api/responses/meta.md#meta-object)
> poster - optional - string, URL to png of poster; accepted aspect ratios: 1:0.675 (IMDb poster type) or 1:1 (square) ; you can use any resolution, as long as the file size is below 100kb; below 50kb is recommended

But i wonder why its failing for only to Android TV application and rest of the platforms are working correctly. So please try to solve this issue either by convert the canvas image supported size or show the movie name instead of crashing the application.

**Screenshots**
![screenrecord](https://github.com/Stremio/stremio-bugs/assets/44891939/11072c51-acb4-476f-8507-6fb009b7c653)

**Android TV:**
 - Device: Android TV Emulator on Android Studio
 - OS: Android TV
 - Version: 1.6.3

**Debug Log**

```
--------- beginning of crash
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: FATAL EXCEPTION: main
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: Process: com.stremio.one, PID: 2805
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: java.lang.RuntimeException: Canvas: trying to draw too large(388800000bytes) bitmap.
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:280)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:109)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.widget.ImageView.onDraw(ImageView.java:1418)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.View.draw(View.java:22350)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21226)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.View.draw(View.java:22353)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21226)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.View.draw(View.java:22353)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at androidx.leanback.widget.ShadowOverlayContainer.draw(ShadowOverlayContainer.java:246)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21226)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5499)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5499)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.kt:235)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.kt:225)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.kt:235)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.kt:225)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:03:31.347 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.kt:235)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.kt:225)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.View.draw(View.java:22353)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at com.android.internal.policy.DecorView.draw(DecorView.java:806)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21226)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4101)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3828)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3099)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1952)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8184)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:731)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-13 01:03:31.348 10079  2805  2805 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
10-13 01:03:31.613  1000   518  7115 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
10-13 01:03:31.618  1000   518  1355 W ActivityTaskManager:   Force finishing activity com.stremio.one/com.stremio.tv.MainActivity
10-13 01:03:31.645  1000   518   543 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
10-13 01:03:31.645  1000   518   543 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
10-13 01:03:31.752  1000   518  1374 I WindowManager: WIN DEATH: Window{c174292 u0 com.stremio.one/com.stremio.tv.MainActivity}
10-13 01:03:31.753  1000   518   607 I ActivityManager: Process com.stremio.one (pid 2805) has died: fg  TOP 
```

**Comment by RamPrasath2812** [comment]
Thank bro

**Comment by MrRight08** [comment]
Facing this issue more than 10 days in Media Fusion addon only when scrolling down, but mobile and web not facing this issue. Please fix this bug as much as early. Thanks in advance

**Comment by tinychimp** [comment]
+1 - Stremio keeps crashing very often on Android TV because of this problem. Please help to prioritize this fix.

**Comment by RamPrasath2812** [comment]
Hi bro, thanks for you effort. Much appreciated, 1.nowadays stremio getting freeze when scrolling down and it will take 15 mins for coming to normal or going to force shutdown the TV.
2. Series files not showing in TV and showing in Mobile only, is there anyway..?

**Comment by SukunaVirus** [comment]
Yeah bro the same happening to me :l

**Comment by jaruba** [comment]
@mhdzumair we will look into the crash, but i do believe this is more of an addon issue, if an addon returns posters that (summed up) can use hundreds of mb or even gb, this is a realistic problem especially on Android TV devices where there is usually very little disk space available, the addon should adapt to the needs of such devices and reduce the poster sizes

**Comment by mhdzumair** [comment]
Thanks @jaruba, I'll handle the poster image conversion from the add-on with proxy image URL to modify it. You can also work on the expected behavior that I mention

> either by convert the canvas image to supported size or show only the movie name instead of crashing the application.

I definitely do the optimization on the add-on side but proposed solution also helpful to other add-on developers.

**Comment by mhdzumair** [comment]
@TRtomasz yes now I use a proxy endpoint to crop the image and modify it runtime for supported size.

**Comment by TRtomasz** [comment]
Thank you, i will close this issue if this has been resolved.
