### ISSUE TITLE
Error while starting streaming server. Error keeps popping up MacOS

### ISSUE THREAD

**Issue by JonnIEnglish** [Stremio/stremio-bugs#642]
I am running MacOS Big Sur version 11.4 (20F71) and whenever I start up Stremio this error keeps popping up every few seconds, even after clicking okay numerous times. 

The full error message is as follows:

Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

(node:6955) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error: listen EADDRINUSE: address already in use :::11470
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at Object.<anonymous> (/Applications/Stremio.app/Contents/MacOS/server.js:36118:16)
    at Object.<anonymous> (/Applications/Stremio.app/Contents/MacOS/server.js:36192:8)
    at __webpack_require__ (/Applications/Stremio.app/Contents/MacOS/server.js:11:34)
    at /Applications/Stremio.app/Contents/MacOS/server.js:45:36
    at Object.<anonymous> (/Applications/Stremio.app/Contents/MacOS/server.js:46:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 11470
}
Error: listen EADDRINUSE: address already in use :::12470
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at Object.<anonymous> (/Applications/Stremio.app/Contents/MacOS/server.js:36129:21)
    at Object.<anonymous> (/Applications/Stremio.app/Contents/MacOS/server.js:36192:8)
    at __webpack_require__ (/Applications/Stremio.app/Contents/MacOS/server.js:11:34)
    at /Applications/Stremio.app/Contents/MacOS/server.js:45:36
    at Object.<anonymous> (/Applications/Stremio.app/Contents/MacOS/server.js:46:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 12470
}
dgram.js:813
    throw errnoException(err, 'setMulticastInterface');
    ^

Error: setMulticastInterface Unknown system error -102
    at Socket.setMulticastInterface (dgram.js:813:11)
    at Timeout.that.update [as _onTimeout] (/Applications/Stremio.app/Contents/MacOS/server.js:73705:63)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  errno: -102,
  code: 'Unknown system error -102',
  syscall: 'setMulticastInterface'
}
(node:7004) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
dgram.js:813
    throw errnoException(err, 'setMulticastInterface');
    ^

Error: setMulticastInterface Unknown system error -102
    at Socket.setMulticastInterface (dgram.js:813:11)
    at EventEmitter.that.update (/Applications/Stremio.app/Contents/MacOS/server.js:73705:63)
    at Socket.<anonymous> (/Applications/Stremio.app/Contents/MacOS/server.js:73646:94)
    at Socket.emit (events.js:327:22)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at startListening (dgram.js:149:10)
    at dgram.js:344:7
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  errno: -102,
  code: 'Unknown system error -102',
  syscall: 'setMulticastInterface'
}
Cannot update settings Unexpected end of JSON input
(node:7046) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
dgram.js:813
    throw errnoException(err, 'setMulticastInterface');
    ^

Error: setMulticastInterface Unknown system error -102
    at Socket.setMulticastInterface (dgram.js:813:11)
    at EventEmitter.that.update (/Applications/Stremio.app/Contents/MacOS/server.js:73705:63)
    at Socket.<anonymous> (/Applications/Stremio.app/Contents/MacOS/server.js:73646:94)
    at Socket.emit (events.js:327:22)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at startListening (dgram.js:149:10)
    at dgram.js:344:7
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  errno: -102,
  code: 'Unknown system error -102',
  syscall: 'setMulticastInterface'
}
Cannot update settings Unexpected end of JSON input
(node:7061) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
dgram.js:813
    throw errnoException(err, 'setMulticastInterface');
    ^

Error: setMulticastInterface Unknown system error -102
    at Socket.setMulticastInterface (dgram.js:813:11)
    at EventEmitter.that.update (/Applications/Stremio.app/Contents/MacOS/server.js:73705:63)
    at Socket.<anonymous> (/Applications/Stremio.app/Contents/MacOS/server.js:73646:94)
    at Socket.emit (events.js:327:22)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at startListening (dgram.js:149:10)
    at dgram.js:344:7
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  errno: -102,
  code: 'Unknown system error -102',
  syscall: 'setMulticastInterface'
}
Cannot update settings Unexpected end of JSON input
(node:7070) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
dgram.js:813
    throw errnoException(err, 'setMulticastInterface');
    ^

Error: setMulticastInterface Unknown system error -102
    at Socket.setMulticastInterface (dgram.js:813:11)
    at EventEmitter.that.update (/Applications/Stremio.app/Contents/MacOS/server.js:73705:63)
    at Socket.<anonymous> (/Applications/Stremio.app/Contents/MacOS/server.js:73646:94)
    at Socket.emit (events.js:327:22)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at startListening (dgram.js:149:10)
    at dgram.js:344:7
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  errno: -102,
  code: 'Unknown system error -102',
  syscall: 'setMulticastInterface'
}

**Comment by TRtomasz** [comment]
something on your system is using port that stremio needs 
`Error: listen EADDRINUSE: address already in use :::11470`

**Comment by JonnIEnglish** [comment]
Oh okay, that makes sense. Thanks for the catch!
Would you be able to recommend a fix?
Many thanks!
