### ISSUE TITLE
Error thrown when Stremio is opened

### ISSUE THREAD

**Issue by griego62** [Stremio/stremio-bugs#683]
When Stremio is opened, it immediately throws the following error:

Stremio streaming server has thrown an error
QProcess::ProcessError code: 1

file:///C:/Users/eldet/AppData/Local/Programs/LNV/Stremio-4/server.js:1149
module.exports = require("url");
^

ReferenceError: require is not defined
at Object.<anonymous> (file:///C:/Users/eldet/AppData/Local/Programs/LNV/Stremio-4/server.js:1149:5)
at __webpack_require__ (file:///C:/Users/eldet/AppData/Local/Programs/LNV/Stremio-4/server.js:11:34)
at Object.<anonymous> (file:///C:/Users/eldet/AppData/Local/Programs/LNV/Stremio-4/server.js:10938:15)
at __webpack_require__ (file:///C:/Users/eldet/AppData/Local/Programs/LNV/Stremio-4/server.js:11:34)
at Object.<anonymous> (file:///C:/Users/eldet/AppData/Local/Programs/LNV/Stremio-4/server.js:35886:24)
at Object.<anonymous> (file:///C:/Users/eldet/AppData/Local/Programs/LNV/Stremio-4/server.js:36192:8)
at __webpack_require__ (file:///C:/Users/eldet/AppData/Local/Programs/LNV/Stremio-4/server.js:11:34)
at file:///C:/Users/eldet/AppData/Local/Programs/LNV/Stremio-4/server.js:45:36
at file:///C:/Users/eldet/AppData/Local/Programs/LNV/Stremio-4/server.js:46:3
at ModuleJob.run (internal/modules/esm/module_job.js:146:23)

The error message can be closed, but it persists, opening various times until it finally stays closed. If I try to open a stream, I get the following errors:

![Screenshot 2024-02-08 195213](https://github.com/Stremio/stremio-bugs/assets/49359787/b76b7bf2-aaa0-4bd9-be92-6b0b1ff1c35b)

I have uninstalled and installed Stremio various times, both with the uninstaller and manually. I have deactivated the Firewall and Antivirus, tried opening Stremio with a VPN, and basically did everything I was instructed to do by Support. They have finally instructed me to report it here as a bug.

I have checked the file structure, and it seems that there is no `stremio` folder in `C:\Users\<my-user>\AppData\Roaming`. On my other laptop, where Stremio is working fine, that folder is there. I copied it, along with its subfolders, and placed it on the affected laptop, but there was no difference noted. So, the result is that Stremio is not streaming anything.

 - OS: Windows 11
 - Default Browser: Firefox
 - Version: 123.0b8 (64-bit)

**Comment by griego62** [comment]
Yes, I do have Node.js installed globally.

    El jueves, 8 de febrero de 2024, 20:22:02 GMT+2, Alexandru Branza ***@***.***> escribió:  
 
 


Do you have Node.js installed globally on your system?

**Comment by jaruba** [comment]
What version of Node.js do you have installed globally? Does the Stremio app work as expected if you uninstall Node.js from your system?

**Comment by griego62** [comment]
My Node.js version was 16.18.0. I uninstalled it, restarted the laptop and tried opening Stremio. The issue persisted as before. I uninstalled Stremio and restarted the laptop again. I opened Stremio and the issue persisted. I attach screenshots. Once again, there is no `stremio` folder in `/AppData/Roaming`.

    El sábado, 10 de febrero de 2024, 01:54:22 GMT+2, Alexandru Branza ***@***.***> escribió:  
 
 


What version of Node.js do you have installed globally? Does the Stremio app work as expected if you uninstall Node.js from your system?

**Comment by griego62** [comment]
I just read the email I sent you and saw that I forgot to mention that I reinstalled Stremio, then I opened it and the issue persisted. That happened after the second restart of my laptop. Sorry, it was late last night 😴El 10 feb 2024 2:31 a. m., Yannis Volos ***@***.***> escribió:
        My Node.js version was 16.18.0. I uninstalled it, restarted the laptop and tried opening Stremio. The issue persisted as before. I uninstalled Stremio and restarted the laptop again. I opened Stremio and the issue persisted. I attach screenshots. Once again, there is no `stremio` folder in `/AppData/Roaming`.
        
        
            
                
                
                    El sábado, 10 de febrero de 2024, 01:54:22 GMT+2, Alexandru Branza ***@***.***> escribió:
                
                
                
                
What version of Node.js do you have installed globally? Does the Stremio app work as expected if you uninstall Node.js from your system?

**Comment by jaruba** [comment]
do you have a "package.json" file in any of these folders:
C:\Users\eldet\AppData\Local\Programs\LNV\
C:\Users\eldet\AppData\Local\Programs\
C:\Users\eldet\AppData\Local\
C:\Users\eldet\AppData\
C:\Users\eldet\
C:\Users\
C:\

If you do, then delete that "package.json" file and try starting the app again

**Comment by griego62** [comment]
Thank you very much. There was a package.json file in `C:\Users\eldet`. Deleting it did the trick. So, I suppose there should be no such file in the root folder `Users` for Stremio to work. I'll keep it in mind.

Kind regards,Yannis

    El sábado, 10 de febrero de 2024, 10:41:17 GMT+2, Alexandru Branza ***@***.***> escribió:  
 
 


do you have a "package.json" file in any of these folders:
C:\Users\eldet\AppData\Local\Programs\LNV
C:\Users\eldet\AppData\Local\Programs
C:\Users\eldet\AppData\Local
C:\Users\eldet\AppData
C:\Users\eldet
C:\Users
C:\

If you do, then delete that "package.json" file and try starting the app again

**Comment by jaruba** [comment]
I think you can install Node.js globally again if you want, I asked you to remove it to ensure that a global Node.js version did not cause this issue, but I don't think that a globally installed version can cause this

but this is the second time that a rogue package.json file caused strange behavior for Stremio

i am happy it is working for you 😊

**Comment by jaruba** [comment]
To better explain this (for historical reasons if you are not personally curious) is the fact that our Node.js server (although self-contained and does not have any dependencies) is still using Node.js, and Node.js will look for a package.json file in any upper directory and consider it as a valid manifest file, we could add a dummy package.json file (even though we don't need it) just to ensure that others are not used, but the issue is that such a dummy file could trigger AV software (which seem to be annoyed by Node.js apps) and that may cause more harm than good as it is extremely rare for anyone to have a package.json file in an upper directory
