### ISSUE TITLE
Stremio keeps throwing error while watching movies/series

### ISSUE THREAD

**Issue by Micas03** [Stremio/stremio-bugs#703]
I've been having this error through multiple updates of Stremio. I have reinstalled various times but have not managed to fix it.

Here is the error code/message I get each time:

Stremio streaming server has thrown an error: "Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

Cannot update settings ENOENT: no such file or directory, open 'C:\Users\micae\AppData\Roaming\stremio\stremio-server\server-settings.json'
(node:15808) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `stremio-runtime --trace-deprecation ...` to show where the warning was created)
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at Socket.onclose (internal/streams/end-of-stream.js:121:38)
    at Socket.emit (events.js:327:22)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at Pipe.<anonymous> (net.js:673:12) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at Socket.onclose (internal/streams/end-of-stream.js:121:38)
    at Socket.emit (events.js:327:22)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at Pipe.<anonymous> (net.js:673:12) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
Error: Live media is not supported
    at Object.get (C:\Users\micae\AppData\Local\Programs\LNV\Stremio-4\server.js:65532:67)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async module.exports.playlist (C:\Users\micae\AppData\Local\Programs\LNV\Stremio-4\server.js:65611:44)
    at async C:\Users\micae\AppData\Local\Programs\LNV\Stremio-4\server.js:63568:28
Error: Live media is not supported
    at Object.get (C:\Users\micae\AppData\Local\Programs\LNV\Stremio-4\server.js:65532:67)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async module.exports.playlist (C:\Users\micae\AppData\Local\Programs\LNV\Stremio-4\server.js:65611:44)
    at async C:\Users\micae\AppData\Local\Programs\LNV\Stremio-4\server.js:63568:28
Error: Probe process exited with code: 1
    at EventEmitter.<anonymous> (C:\Users\micae\AppData\Local\Programs\LNV\Stremio-4\server.js:29830:156)
    at Object.onceWrapper (events.js:422:26)
    at EventEmitter.emit (events.js:315:20)
    at EventEmitter.emit (domain.js:486:12)
    at ChildProcess.<anonymous> (C:\Users\micae\AppData\Local\Programs\LNV\Stremio-4\server.js:65184:37)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:486:12)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at Pipe.<anonymous> (net.js:673:12)
Error: Probe process exited with code: 1
    at EventEmitter.<anonymous> (C:\Users\micae\AppData\Local\Programs\LNV\Stremio-4\server.js:29830:156)
    at Object.onceWrapper (events.js:422:26)
    at EventEmitter.emit (events.js:315:20)
    at EventEmitter.emit (domain.js:486:12)
    at ChildProcess.<anonymous> (C:\Users\micae\AppData\Local\Programs\LNV\Stremio-4\server.js:65184:37)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:486:12)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
Error: Probe process exited with code: 1
    at EventEmitter.<anonymous> (C:\Users\micae\AppData\Local\Programs\LNV\Stremio-4\server.js:29830:156)
    at Object.onceWrapper (events.js:422:26)
    at EventEmitter.emit (events.js:315:20)
    at EventEmitter.emit (domain.js:486:12)
    at ChildProcess.<anonymous> (C:\Users\micae\AppData\Local\Programs\LNV\Stremio-4\server.js:65184:37)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:486:12)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)

<--- Last few GCs --->

[15808:03C865F0]  1650091 ms: Mark-sweep 21.7 (24.6) -> 21.6 (25.8) MB, 1.3 / 0.0 ms  (+ 10.2 ms in 49 steps since start of marking, biggest step 0.5 ms, walltime since start of marking 14 ms) (average mu = 0.997, current mu = 0.999) finalize incremental [15808:03C865F0]  1651390 ms: Scavenge 21.7 (24.8) -> 21.6 (25.8) MB, 0.3 / 0.0 ms  (average mu = 0.997, current mu = 0.999) external memory pressure 

<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
(node:12544) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `stremio-runtime --trace-deprecation ...` to show where the warning was created)
Failed executing external player command: null
internal/buffer.js:951
class FastBuffer extends Uint8Array {}
^

RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at new FastBuffer (internal/buffer.js:951:1)
    at createUnsafeBuffer (buffer.js:152:12)
    at allocate (buffer.js:422:10)
    at Function.allocUnsafe (buffer.js:387:10)
    at Function.concat (buffer.js:567:25)
    at Socket.read (C:\Users\micae\AppData\Local\Programs\LNV\Stremio-4\server.js:70275:62)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at emitReadable_ (_stream_readable.js:569:12)
    at processTicksAndRejections (internal/process/task_queues.js:79:21)" or other error: "Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

(node:8716) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use stremio-runtime --trace-deprecation ... to show where the warning was created)

<--- Last few GCs --->

[8716:04226000]  1725341 ms: Scavenge 22.9 (25.2) -> 22.7 (26.2) MB, 1.2 / 0.0 ms  (average mu = 0.996, current mu = 0.997) external memory pressure 
[8716:04226000]  1725388 ms: Mark-sweep 22.7 (28.2) -> 22.7 (28.2) MB, 4.2 / 0.0 ms  (+ 38.7 ms in 40 steps since start of marking, biggest step 3.9 ms, walltime since start of marking 47 ms) (average mu = 0.996, current mu = 0.997) finalize incremental m

<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory"

This error appears while I'm streaming out of nowhere, it stays in the foreground but the stream doesn't stop, it continues to appear as if nothing had happened

**Screenshots**
![IMG20240221210120](https://github.com/Stremio/stremio-bugs/assets/157054842/7d926e74-d084-4410-9ab6-4b82edb26d54)
![image1](https://github.com/Stremio/stremio-bugs/assets/157054842/bce5cd38-d623-4b9a-9774-6dfba3ef9e5a)

**Desktop (please complete the following information):**
 - OS: [Win 10]
 - Browser [chrome]
 - Version [22]
 - Ram: 32GB

**Comment by TRtomasz** [comment]
Looks like something on your system is blockng the local streaming server, i have no means to debug what it is but could be a vpn/proxy/firewall etc
