### ISSUE TITLE
Chromecast hangs

### ISSUE THREAD

**Issue by kripskroll** [Stremio/stremio-bugs#8]
When launching Chromecast, It detects correctly Chromecast and then send the error in the console.
Stremio version : 3.3.1 fresh install

Console output :
[10326:1107/001413:INFO:CONSOLE(1)] "Subtitles: expecting correct subtitles", source: file:///home/stef/Developpement/Stremio3.3.1/resources/app.asar/blob.js (1)
[10326:1107/001416:INFO:CONSOLE(1)] "TypeError: Cannot read property 'mediaSessionId' of null
    at MediaController.sessionRequest (/home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/node_modules/castv2-client/lib/controllers/media.js:78:44)
    at /home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/index.js:191:17
    at apply (/home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/node_modules/thunky/index.js:16:28)
    at /home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/node_modules/thunky/index.js:20:25
    at /home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/index.js:77:11
    at PlatformSender.join (/home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/node_modules/castv2-client/lib/senders/platform.js:88:3)
    at /home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/node_modules/castv2-client/lib/senders/platform.js:102:10
    at /home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/node_modules/castv2-client/lib/controllers/receiver.js:53:5
    at ReceiverController.onmessage (/home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/node_modules/castv2-client/lib/controllers/request-response.js:27:7)
    at emitTwo (events.js:92:20)
    at ReceiverController.emit (events.js:172:7)
    at Channel.onmessage (/home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/node_modules/castv2-client/lib/controllers/controller.js:16:10)
    at emitTwo (events.js:87:13)
    at Channel.emit (events.js:172:7)
    at Client.onmessage (/home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/node_modules/castv2-client/node_modules/castv2/lib/channel.js:23:10)
    at emitMany (events.js:113:20)
    at Client.emit (events.js:182:7)", source: file:///home/stef/Developpement/Stremio3.3.1/resources/app.asar/blob.js (1)
[10326:1107/001420:INFO:CONSOLE(49)] "Uncaught, unspecified "error" event. ([object Object])", source: /home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/airplay-js/airplay/client.js (49)
[10326:1107/001450:INFO:CONSOLE(49)] "Uncaught, unspecified "error" event. ([object Object])", source: /home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/airplay-js/airplay/client.js (49)
[10326:1107/001500:INFO:CONSOLE(3)] "TypeError: Cannot read property 'mediaSessionId' of null", source: file:///home/stef/Developpement/Stremio3.3.1/resources/app.asar/blob.js (3)
setting window mode to: main with aspect: undefined
[10326:1107/001500:INFO:CONSOLE(3)] "TypeError: Cannot read property 'mediaSessionId' of null", source: file:///home/stef/Developpement/Stremio3.3.1/resources/app.asar/blob.js (3)
[10326:1107/001504:INFO:CONSOLE(141)] "Error: <!DOCTYPE html>
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>", source: /home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/linvodb3/addons/linvo-sync.js (141)
[10326:1107/001513:INFO:CONSOLE(3)] "Engine a45129e59d8750f9da982f53552b1e4f0457ee9f is inactive, destroying it", source: file:///home/stef/Developpement/Stremio3.3.1/resources/app.asar/blob.js (3)
....

Thanks

**Comment by Ivshti** [comment]
Thanks for reporting this! It seems to happen in more and more cases. Will try to take a look at it asap

**Comment by kripskroll** [comment]
If you need any logs using debug commands, feel free to ask.
Good luck ;)

**Comment by kripskroll** [comment]
Latest 3.3.2 is going one step further. But still hangs.
Now I can see the image thumbnails of the movie on the TV through the Cast. But gauge is always moving and never stops before to crach.

Here is exiting output console at the time of the crash. Feel free to ask for more if needed using debug commands if needed :

[31420:1108/133153:INFO:CONSOLE(1)] "TypeError: Cannot read property 'mediaSessionId' of undefined
    at MediaController.sessionRequest (/home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/node_modules/castv2-client/lib/controllers/media.js:78:44)
    at /home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/index.js:191:17
    at apply (/home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/node_modules/thunky/index.js:16:28)
    at /home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/node_modules/thunky/index.js:27:3
    at EventEmitter.player.request (/home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/index.js:189:7)
    at EventEmitter.player.subtitles (/home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/index.js:181:14)
    at file:///home/stef/Developpement/Stremio3.3.1/resources/app.asar/blob.js:3:18195
    at /home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/node_modules/castv2-client/lib/controllers/media.js:68:14
    at MediaController.onmessage (/home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/node_modules/castv2-client/lib/controllers/request-response.js:27:7)
    at emitTwo (events.js:92:20)
    at MediaController.emit (events.js:172:7)
    at Channel.onmessage (/home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/node_modules/castv2-client/lib/controllers/controller.js:16:10)
    at emitTwo (events.js:87:13)
    at Channel.emit (events.js:172:7)
    at Client.onmessage (/home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/node_modules/castv2-client/node_modules/castv2/lib/channel.js:23:10)
    at emitMany (events.js:113:20)", source: file:///home/stef/Developpement/Stremio3.3.1/resources/app.asar/blob.js (1)
[31420:1108/133154:INFO:CONSOLE(1)] "Error: Illegal wire type for field Message.Field .extensions.api.cast_channel.CastMessage.payload_type: 5 (0 expected)
    at Error (native)
    at ProtoBuf.Reflect.FieldPrototype.decode (/home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/node_modules/castv2-client/node_modules/castv2/node_modules/protobufjs/dist/ProtoBuf.js:3043:27)
    at ProtoBuf.Reflect.MessagePrototype.decode (/home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/node_modules/castv2-client/node_modules/castv2/node_modules/protobufjs/dist/ProtoBuf.js:2462:49)
    at Function.Message.decode (/home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/node_modules/castv2-client/node_modules/castv2/node_modules/protobufjs/dist/ProtoBuf.js:2190:41)
    at Object.module.exports.(anonymous function).parse (/home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/node_modules/castv2-client/node_modules/castv2/lib/proto.js:22:34)
    at PacketStreamWrapper.onpacket (/home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/node_modules/castv2-client/node_modules/castv2/lib/client.js:61:31)
    at emitOne (events.js:77:13)
    at PacketStreamWrapper.emit (events.js:169:7)
    at TLSSocket.<anonymous> (/home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/node_modules/castv2-client/node_modules/castv2/lib/packet-stream-wrapper.js:28:16)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at emitReadable_ (_stream_readable.js:411:10)
    at emitReadable (_stream_readable.js:405:7)
    at readableAddChunk (_stream_readable.js:157:11)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:523:20)", source: file:///home/stef/Developpement/Stremio3.3.1/resources/app.asar/blob.js (1)
[31420:1108/133154:INFO:CONSOLE(1)] "Error: Illegal wire type for unknown field 13 in Message .extensions.api.cast_channel.CastMessage#decode: 7
    at Error (native)
    at ProtoBuf.Reflect.MessagePrototype.decode (/home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/node_modules/castv2-client/node_modules/castv2/node_modules/protobufjs/dist/ProtoBuf.js:2455:39)
    at Function.Message.decode (/home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/node_modules/castv2-client/node_modules/castv2/node_modules/protobufjs/dist/ProtoBuf.js:2190:41)
    at Object.module.exports.(anonymous function).parse (/home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/node_modules/castv2-client/node_modules/castv2/lib/proto.js:22:34)
    at PacketStreamWrapper.onpacket (/home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/node_modules/castv2-client/node_modules/castv2/lib/client.js:61:31)
    at emitOne (events.js:77:13)
    at PacketStreamWrapper.emit (events.js:169:7)
    at TLSSocket.<anonymous> (/home/stef/Developpement/Stremio3.3.1/resources/app.asar/node_modules/chromecasts/node_modules/castv2-client/node_modules/castv2/lib/packet-stream-wrapper.js:28:16)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at emitReadable_ (_stream_readable.js:411:10)
    at emitReadable (_stream_readable.js:405:7)
    at readableAddChunk (_stream_readable.js:157:11)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:523:20)", source: file:///home/stef/Developpement/Stremio3.3.1/resources/app.asar/blob.js (1)

**Comment by Ivshti** [comment]
Thanks for the detailed log.

Btw nothing is changed in terms of casting ever since 3.2.0. I've just hadn't the time to look at it.
So the poster appearing now is quite interesting.

The chromecast module we're using is a bit chaotic.

**Comment by kripskroll** [comment]
Hi,

I probably found the reason of the issue : FFMPEG needs to be installed and found by Stremio. If I have it installed, then casting is working. 

Unfortunately, the streaming is not very good with a lot of freezes and sounds that is going on and off.

Thanks for your effort

**Comment by Ivshti** [comment]
@kripskroll I honestly doubt this is fixed. I haven't changed anything, and I think the module is almost (or entirely) fixed version.

Please make sure

I've experienced this issue before too, but it's been random, on-and-off, and it depended on my chromecast. try re-starting your chromecast, the issue may re-appear

**Comment by Ivshti** [comment]
Actually it makes sense, since mafintosh/chromecasts module is updated pretty often.

Good
