### ISSUE TITLE
macOS app can't start streaming server

### ISSUE THREAD

**Issue by erazemk** [Stremio/stremio-bugs#909]
**Describe the bug**
When starting the latest version of the macOS app (4.4.168), I get the error `Error while starting streaming server. Please try to restart stremio. If it happens again please contact the Stremio support team for assistance`.

When expanding the details, this is what is shown:
```
Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

(node:3232) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn pgrep ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn pgrep',
  path: 'pgrep',
  spawnargs: [ '-P', 3236 ]
}
(node:3246) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn pgrep ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn pgrep',
  path: 'pgrep',
  spawnargs: [ '-P', 3248 ]
}
(node:3259) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn pgrep ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn pgrep',
  path: 'pgrep',
  spawnargs: [ '-P', 3261 ]
}
```

**To Reproduce**
1. Install the latest version of the macOS app (4.4.168)
2. Open it
3. See error popup

**Expected behavior**
Stremio server starts up properly.

**Screenshots**
<img width="420" alt="image" src="https://github.com/user-attachments/assets/bd0069a8-9c94-40b1-be56-fdcb2cb79cd4">

**Desktop:**
 - OS: macOS
 - Browser: not applicable
 - Version: 4.4.168

**Comment by TRtomasz** [comment]
did you enable rosetta?

**Comment by erazemk** [comment]
Yes

**Comment by TRtomasz** [comment]
It starts just fine here on our side and since you are the only one with such issue, either you modified server.js file or use some modified Stremio version. Or something modified your path/ installed apps that pgrep cant be started or you have

**Comment by erazemk** [comment]
@TRtomasz This is the error I get after a clean install of stremio:

```
Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

Cannot update settings ENOENT: no such file or directory, open '/Users/erazemk/Library/Application Support/stremio-server/server-settings.json'
(node:71707) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn pgrep ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn pgrep',
  path: 'pgrep',
  spawnargs: [ '-P', 71723 ]
}
```

I have not modified any files or stremio version.

**Comment by erazemk** [comment]
pgrep can be run in the terminal, I use fish shell as my default.
