### ISSUE TITLE
Stremio fails to open magnet links and .torrent files

### ISSUE THREAD

**Issue by wdiasjunior** [Stremio/stremio-bugs#943]
**Describe the bug**
I get the error message below when attempting to open magnet links and .torrent files, along with a toast message `ERR_OPENING_MEDIA failed to fetch`. 

```
Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

(node:21622) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
TypeError: WebSocket is not a constructor
    at new Socket (/opt/stremio/server.js:126172:14)
    at WebSocketTracker._openSocket (/opt/stremio/server.js:12342:50)
    at new WebSocketTracker (/opt/stremio/server.js:12266:8)
    at /opt/stremio/server.js:11554:16
    at Array.map (<anonymous>)
    at new Client (/opt/stremio/server.js:11546:6)
    at Tracker.run (/opt/stremio/server.js:108026:22)
    at /opt/stremio/server.js:107965:5
    at Array.forEach (<anonymous>)
    at peerSearch.run (/opt/stremio/server.js:107962:48)
    at new peerSearch (/opt/stremio/server.js:107984:7)
    at createEngine (/opt/stremio/server.js:46171:9)
    at /opt/stremio/server.js:46365:5
    at Layer.handle [as handle_request] (/opt/stremio/server.js:122233:5)
    at next (/opt/stremio/server.js:122466:13)
    at Route.dispatch (/opt/stremio/server.js:122431:3)
TypeError: WebSocket is not a constructor
    at new Socket (/opt/stremio/server.js:126172:14)
    at WebSocketTracker._openSocket (/opt/stremio/server.js:12342:50)
    at new WebSocketTracker (/opt/stremio/server.js:12266:8)
    at /opt/stremio/server.js:11554:16
    at Array.map (<anonymous>)
    at new Client (/opt/stremio/server.js:11546:6)
    at Tracker.run (/opt/stremio/server.js:108026:22)
    at /opt/stremio/server.js:107965:5
    at Array.forEach (<anonymous>)
    at peerSearch.run (/opt/stremio/server.js:107962:48)
    at new peerSearch (/opt/stremio/server.js:107984:7)
    at createEngine (/opt/stremio/server.js:46171:9)
    at /opt/stremio/server.js:46365:5
    at Layer.handle [as handle_request] (/opt/stremio/server.js:122233:5)
    at next (/opt/stremio/server.js:122466:13)
    at Route.dispatch (/opt/stremio/server.js:122431:3)
node:_http_server:345
    throw new ERR_HTTP_HEADERS_SENT('write');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot write headers after they are sent to the client
    at ServerResponse.writeHead (node:_http_server:345:11)
    at /opt/stremio/server.js:46366:13
    at EventEmitter.<anonymous> (/opt/stremio/server.js:46142:58)
    at Object.onceWrapper (node:events:633:26)
    at EventEmitter.emit (node:events:530:35)
    at EventEmitter.emit (node:domain:488:12)
    at /opt/stremio/server.js:46187:35
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ERR_HTTP_HEADERS_SENT'
}

Node.js v20.12.2
```

 - OS: Arch Linux
 - Version 4.4.168 (AUR)

**Comment by TRtomasz** [comment]
Perhaps there is an issue with your node.js version  you can try either older node.js version or try installing `ws` globally
