### ISSUE TITLE
Streaming server throws ProcessError 1

### ISSUE THREAD

**Issue by m-a-x-s-e-e-l-i-g** [Stremio/stremio-bugs#962]
**Describe the bug**
While streaming something in the app sometimes an error pops up saying Stremio streaming server has thrown an error. It pauses the stream. When I navigate back and forward I'm able to watch again. See attached error log.

**To Reproduce**
This occurs after having watched a couple of shows consequently.
I seems to happen when Hue Sync is running and actively syncing with an entertainment area. 

**Expected behavior**
No error. ㄟ(≧◇≦)ㄏ

**Desktop:**
Stremio 4.4.168
Web UI 4.4 1/2
Server 4.20.8
Windows 11 Pro 22H2 22621.4317
Hue Sync 1.12.1.65

**Additional context**
```
Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

(node:10680) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `stremio-runtime --trace-deprecation ...` to show where the warning was created)
Engine invalid piece 28 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 28 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 28 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 28 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 28 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 28 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 28 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 220 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 220 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 220 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 397 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 397 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 397 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 397 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 397 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 397 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 397 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 473 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 397 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 473 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 397 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 571 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 586 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 586 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 586 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 586 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 586 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 586 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 1007 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 1007 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 1007 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 1007 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
Engine invalid piece 1007 for 09c0fceece4c36f50c4eb76314107a9dd8c5e0da
internal/buffer.js:951
class FastBuffer extends Uint8Array {}
^

RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at new FastBuffer (internal/buffer.js:951:1)
    at Function.alloc (buffer.js:378:10)
    at Object.read (C:\Users\x\AppData\Local\Programs\LNV\Stremio-4\server.js:70882:52)
    at C:\Users\x\AppData\Local\Programs\LNV\Stremio-4\server.js:70906:22
    at C:\Users\x\AppData\Local\Programs\LNV\Stremio-4\server.js:7658:24
    at Object.async.forEachOf.async.eachOf (C:\Users\x\AppData\Local\Programs\LNV\Stremio-4\server.js:7899:13)
    at Object.async.forEach.async.each (C:\Users\x\AppData\Local\Programs\LNV\Stremio-4\server.js:7891:26)
    at that.read (C:\Users\x\AppData\Local\Programs\LNV\Stremio-4\server.js:70901:19)
    at Timeout._onTimeout (C:\Users\x\AppData\Local\Programs\LNV\Stremio-4\server.js:70715:20)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:9136) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `stremio-runtime --trace-deprecation ...` to show where the warning was created)
internal/buffer.js:951
class FastBuffer extends Uint8Array {}
^

RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at new FastBuffer (internal/buffer.js:951:1)
    at Function.alloc (buffer.js:378:10)
    at Object.read (C:\Users\x\AppData\Local\Programs\LNV\Stremio-4\server.js:70882:52)
    at C:\Users\x\AppData\Local\Programs\LNV\Stremio-4\server.js:70906:22
    at C:\Users\x\AppData\Local\Programs\LNV\Stremio-4\server.js:7658:24
    at Object.async.forEachOf.async.eachOf (C:\Users\x\AppData\Local\Programs\LNV\Stremio-4\server.js:7899:13)
    at Object.async.forEach.async.each (C:\Users\x\AppData\Local\Programs\LNV\Stremio-4\server.js:7891:26)
    at that.read (C:\Users\x\AppData\Local\Programs\LNV\Stremio-4\server.js:70901:19)
    at Timeout._onTimeout (C:\Users\x\AppData\Local\Programs\LNV\Stremio-4\server.js:70715:20)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:22288) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `stremio-runtime --trace-deprecation ...` to show where the warning was created)
internal/buffer.js:951
class FastBuffer extends Uint8Array {}
^

RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at new FastBuffer (internal/buffer.js:951:1)
    at Function.alloc (buffer.js:378:10)
    at Object.read (C:\Users\x\AppData\Local\Programs\LNV\Stremio-4\server.js:70882:52)
    at C:\Users\x\AppData\Local\Programs\LNV\Stremio-4\server.js:70906:22
    at C:\Users\x\AppData\Local\Programs\LNV\Stremio-4\server.js:7658:24
    at Object.async.forEachOf.async.eachOf (C:\Users\x\AppData\Local\Programs\LNV\Stremio-4\server.js:7899:13)
    at Object.async.forEach.async.each (C:\Users\x\AppData\Local\Programs\LNV\Stremio-4\server.js:7891:26)
    at that.read (C:\Users\x\AppData\Local\Programs\LNV\Stremio-4\server.js:70901:19)
    at Timeout._onTimeout (C:\Users\x\AppData\Local\Programs\LNV\Stremio-4\server.js:70715:20)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

**Comment by m-a-x-s-e-e-l-i-g** [comment]
Good you closed this bullshit issue. I still don't understand why this occurs, but when I don't  have Hue Sync running it won't happen 😂
